(function(){
 'use strict';
 var api,changed,modal,info,series,formState=null,current=null;
 var labels={preview:'Bozza da creare',creating:'Creazione in corso',created:'Creata',create_rejected:'Da correggere',create_unknown:'Creazione da verificare',sending:'Invio in corso',sent:'Invio richiesto',send_unknown:'Invio da verificare'};
 function E(id){return document.getElementById(id)}
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
 function money(v){return Number(v||0).toLocaleString('it-IT',{style:'currency',currency:'EUR'})}
 function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Rome'}).format(new Date())}
 function error(e){var box=E('ficError');if(box){box.textContent=e.message||String(e);box.hidden=false}}
 function layout(title){modal.innerHTML='<section class="ficCard" role="dialog" aria-modal="true" aria-label="'+esc(title)+'"><header><div><small>MOLOGNI COMPANY S.R.L.</small><h2>'+esc(title)+'</h2></div><button type="button" id="ficClose">Chiudi</button></header><nav><button id="ficNew" type="button">Nuova fattura</button><button id="ficList" type="button">Bozze e documenti</button></nav><div id="ficError" role="alert" hidden></div><main id="ficBody"></main></section>';E('ficClose').onclick=function(){modal.remove();modal=null};E('ficNew').onclick=function(){loadForm()};E('ficList').onclick=list;}
 function run(button,work){button.disabled=true;var old=button.textContent;button.textContent='Attendi…';E('ficError').hidden=true;Promise.resolve().then(work).catch(error).finally(function(){if(button.isConnected){button.disabled=false;button.textContent=old}})}
 function field(id,label,value,type,extra){return '<label>'+esc(label)+'<input id="'+id+'" type="'+(type||'text')+'" value="'+esc(value)+'" '+(extra||'')+'></label>'}
 function option(v,label,selected){return '<option value="'+esc(v)+'"'+(selected?' selected':'')+'>'+esc(label)+'</option>'}
 function select(id,label,options){return '<label>'+esc(label)+'<select id="'+id+'">'+options+'</select></label>'}
 function values(){var b={series:E('ficSeries').value,date:E('ficDate').value,channel:E('ficChannel').value,td:E('ficTd')?E('ficTd').value:'TD01',entity:{},items:[],subject:E('ficSubject').value,notes:E('ficNotes').value,stamp_duty:E('ficStamp').value,payment_method:E('ficPayment').value,due_date:E('ficDue').value,draft_id:formState&&formState.draft_id};['name','type','vat_number','tax_code','address_street','address_postal_code','address_city','address_province','country','ei_code','certified_email'].forEach(function(k){b.entity[k]=E('fic_'+k).value});E('ficItems').querySelectorAll('tr').forEach(function(r){b.items.push({name:r.querySelector('[data-k="name"]').value,qty:r.querySelector('[data-k="qty"]').value,net_price:r.querySelector('[data-k="net_price"]').value,vat_id:r.querySelector('[data-k="vat_id"]').value})});if(E('ficOriginalNumber')){b.original_number=E('ficOriginalNumber').value;b.original_date=E('ficOriginalDate').value}return b}
 function row(v){v=v||{};var tr=document.createElement('tr');tr.innerHTML='<td><input data-k="name" aria-label="Descrizione riga" value="'+esc(v.name)+'" required maxlength="500"></td><td><input data-k="qty" aria-label="Quantità" type="number" min="0.001" step="any" value="'+esc(v.qty||1)+'" required></td><td><input data-k="net_price" aria-label="Prezzo netto unitario" type="number" min="0" step="any" value="'+esc(v.net_price??'')+'" required></td><td><select data-k="vat_id" aria-label="Aliquota IVA" required>'+option('','Scegli IVA',!v.vat_id)+info.vat_types_list.filter(function(x){return !x.is_disabled}).map(function(x){return option(x.id,x.value+'% · '+(x.description||x.ei_type||''),Number(v.vat_id)===x.id)}).join('')+'</select></td><td><button type="button" aria-label="Rimuovi riga">×</button></td>';tr.querySelector('button').onclick=function(){tr.remove()};E('ficItems').appendChild(tr)}
 function renderForm(b){
  formState=b;var e=b.entity||{},foreign=b.series==='foreign';layout('Nuova fattura');
  var chosen=series.find(function(s){return s.code===b.series&&s.year===Number(b.date.slice(0,4))});
  E('ficBody').innerHTML='<form id="ficForm"><div class="ficGrid">'+select('ficSeries','Serie',series.map(function(s){return option(s.code,s.label,b.series===s.code)}).join(''))+field('ficDate','Data documento',b.date,'date','required')+'<div class="ficHint">Prossimo numero indicativo: <strong>'+(chosen?esc((chosen.last_number+1)+chosen.suffix):'serie non configurata')+'</strong></div>'+select('ficChannel','Tipo di fatturazione',foreign?option('sdi','Autofattura elettronica',true):option('','Scegli',!b.channel)+option('sdi','Fattura commerciale · invio SDI',b.channel==='sdi')+option('health','Documento sanitario a persona fisica · senza SDI',b.channel==='health'))+'</div>';
  var f=E('ficForm');
  if(foreign)f.insertAdjacentHTML('beforeend','<div class="ficGrid">'+select('ficTd','Tipo di documento',option('','Scegli',!b.td)+option('TD17','TD17 · Servizi dall’estero',b.td==='TD17')+option('TD18','TD18 · Beni intracomunitari',b.td==='TD18')+option('TD19','TD19 · Beni, art. 17 comma 2',b.td==='TD19'))+field('ficOriginalNumber','Numero fattura del fornitore',b.original_number,'text','required')+field('ficOriginalDate','Data fattura del fornitore',b.original_date,'date','required')+'</div>');
  f.insertAdjacentHTML('beforeend','<h3>'+(foreign?'Fornitore estero':'Intestatario')+'</h3><div class="ficGrid">'+field('fic_name','Nome completo / ragione sociale',e.name,'text','required')+select('fic_type','Soggetto',option('person','Persona fisica',e.type==='person')+option('company','Azienda',e.type!=='person'))+field('fic_vat_number','Partita IVA / identificativo fiscale',e.vat_number)+field('fic_tax_code','Codice fiscale',e.tax_code)+field('fic_address_street','Indirizzo',e.address_street,'text','required')+field('fic_address_postal_code','CAP',e.address_postal_code,'text','required')+field('fic_address_city','Comune',e.address_city,'text','required')+field('fic_address_province','Provincia',e.address_province,'text','maxlength="2"')+select('fic_country','Paese',info.countries_list.map(function(c){return option(c,c,c===(e.country||'Italia'))}).join(''))+field('fic_ei_code','Codice destinatario SDI',e.ei_code,'text','maxlength="7"')+field('fic_certified_email','PEC',e.certified_email,'email')+'</div><h3>Righe del documento</h3><div class="ficTableScroll"><table><thead><tr><th>Descrizione</th><th>Quantità</th><th>Prezzo netto €</th><th>IVA</th><th></th></tr></thead><tbody id="ficItems"></tbody></table></div><button id="ficAdd" type="button">+ Aggiungi riga</button><div class="ficGrid">'+field('ficSubject','Oggetto',b.subject)+field('ficStamp','Bollo €',b.stamp_duty||0,'number','min="0" max="2" step="2"')+select('ficPayment','Modalità di pagamento',option('','Scegli',!b.payment_method)+[['MP05','Bonifico'],['MP08','Carta'],['MP01','Contanti'],['MP02','Assegno'],['MP12','Ri.Ba.']].map(function(p){return option(p[0],p[1],p[0]===b.payment_method)}).join(''))+field('ficDue','Scadenza pagamento',b.due_date||b.date,'date','required')+'</div><label>Note<textarea id="ficNotes" maxlength="2000">'+esc(b.notes)+'</textarea></label><p class="ficHint">Il pagamento verrà registrato come da incassare. Per i documenti sanitari questa funzione non effettua l’invio al Sistema TS.</p><footer><button type="submit" class="ficPrimary" id="ficPreview">Calcola e mostra anteprima</button></footer>');
  (b.items&&b.items.length?b.items:[{}]).forEach(row);E('ficAdd').onclick=function(){row()};E('ficSeries').onchange=function(){var next=values();next.series=this.value;next.draft_id=null;next.channel=next.series==='foreign'?'sdi':'';loadForm(next)};
  f.onsubmit=function(ev){ev.preventDefault();var payload=values();formState=payload;run(E('ficPreview'),async function(){current=await api('fic_preview',payload);preview(current,false)})};
 }
 function fromDraft(d){var p=d.document,x=p.ei_raw?.FatturaElettronicaBody?.DatiGenerali||{},ref=x.DatiFattureCollegate?.[0]||{};return {draft_id:d.id,series:d.series,date:p.date,channel:p.e_invoice?'sdi':'health',td:x.DatiGeneraliDocumento?.TipoDocumento,entity:p.entity,items:p.items_list.map(function(i){return {name:i.name,qty:i.qty,net_price:i.net_price,vat_id:i.vat.id}}),subject:p.visible_subject,notes:p.notes,stamp_duty:p.stamp_duty,payment_method:p.ei_data.payment_method,due_date:p.payments_list[0].due_date,original_number:ref.IdDocumento,original_date:ref.Data}}
 async function loadForm(b){layout('Nuova fattura');E('ficBody').textContent='Caricamento dati…';try{b=b||{series:'retail',date:today(),entity:{type:'person',country:'Italia'},items:[]};var r=await api('fic_form',{series:b.series});info=r.info;series=r.series;renderForm(b)}catch(e){error(e)}}
 function preview(d,sendReview){
  current=d;layout(sendReview?'Verifica prima dell’invio':'Anteprima fattura');var p=d.remote||d.document,entity=p.entity||{},num=d.number||p.number||d.suggested_number,td=d.document.ei_raw?.FatturaElettronicaBody?.DatiGenerali?.DatiGeneraliDocumento?.TipoDocumento;
  E('ficBody').innerHTML='<div class="ficSummary"><strong>Documento '+esc(num+p.numeration)+'</strong><span>'+esc(p.date)+' · '+esc(td)+'</span><strong>'+esc(entity.name)+'</strong><span>'+esc([entity.address_street,entity.address_postal_code,entity.address_city,entity.country].filter(Boolean).join(', '))+'</span><span>'+esc(entity.vat_number||entity.tax_code)+'</span><span>Destinazione: '+esc(p.e_invoice?(entity.ei_code||'SDI'):'Documento senza invio SDI')+'</span></div><div class="ficTableScroll"><table><thead><tr><th>Descrizione</th><th>Quantità</th><th>Prezzo netto</th><th>IVA</th></tr></thead><tbody>'+p.items_list.map(function(i){return '<tr><td>'+esc(i.name)+'</td><td>'+esc(i.qty)+'</td><td>'+money(i.net_price)+'</td><td>'+esc(i.vat?.value!=null?i.vat.value+'%':(info?.vat_types_list?.find(function(v){return v.id===i.vat?.id})?.value??'')+'%')+'</td></tr>'}).join('')+'</tbody></table></div><p class="ficTotal">Totale: '+money(p.amount_gross??d.totals.amount_gross)+'</p><p>'+esc(p.visible_subject||'')+'</p><p>'+esc(p.notes||'')+'</p><p>Stato: <strong>'+esc(labels[d.state]||d.state)+'</strong>'+(d.remote?' · SDI: '+esc(d.remote.ei_status||'non previsto'):'')+'</p>'+(d.last_error?'<p role="alert">'+esc(d.last_error)+'</p>':'')+'<footer id="ficActions"></footer>';
  var extra=document.createElement('div');extra.className='ficHint';
  var linked=d.document.ei_raw?.FatturaElettronicaBody?.DatiGenerali?.DatiFattureCollegate?.[0];
  extra.innerHTML='<p>Imponibile: '+money(d.totals.amount_net)+' · IVA: '+money(d.totals.amount_vat)+' · Bollo: '+money(p.stamp_duty)+' · Da pagare: <strong>'+money(d.totals.amount_due??d.totals.amount_gross)+'</strong></p><p>Pagamento: '+esc(p.ei_data?.payment_method)+' · Scadenza: '+esc(p.payments_list?.[0]?.due_date)+'</p>'+(linked?'<p>Fattura estera collegata: <strong>'+esc(linked.IdDocumento)+'</strong> del '+esc(linked.Data)+'</p>':'');
  E('ficActions').before(extra);
  var a=E('ficActions');
  if(['preview','create_rejected'].includes(d.state)){
   a.innerHTML='<button id="ficEdit" type="button">Modifica</button><label class="ficCheck"><input id="ficDateConfirm" type="checkbox">Ho verificato la data rispetto all’ultima fattura della serie</label><button id="ficCreate" type="button" class="ficPrimary">Conferma creazione in Fatture in Cloud</button>';
   E('ficEdit').onclick=function(){loadForm(fromDraft(d))};E('ficCreate').onclick=function(){if(!E('ficDateConfirm').checked)return error(new Error('Conferma il controllo della data'));run(this,async function(){var created=await api('fic_create',{id:d.id,confirm_create:true,confirm_date:true});changed();preview(created,false)})};
  }else if(d.provider_id){
   a.innerHTML='<button id="ficStatus" type="button">Aggiorna stato e visualizza PDF</button>';
   E('ficStatus').onclick=function(){run(this,async function(){preview(await api('fic_document',{id:d.id}),false)})};
   if(d.remote?.url){var u=new URL(d.remote.url);if(u.protocol==='https:'){var link=document.createElement('a');link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';link.referrerPolicy='no-referrer';link.textContent='Apri PDF';a.appendChild(link)}}
   if(d.document.e_invoice&&d.state==='created'){
    var send=document.createElement('button');send.type='button';send.className='ficPrimary';send.textContent=sendReview?'Conferma invio allo SDI':'Prepara invio allo SDI';a.appendChild(send);
    send.onclick=function(){run(send,async function(){if(!sendReview){preview(await api('fic_document',{id:d.id}),true);return}var sent=await api('fic_send',{id:d.id,review_hash:d.review_hash,confirm_send:true});changed();preview(sent,false)})};
   }
  }
 }
 async function list(){layout('Bozze e documenti');E('ficBody').textContent='Caricamento…';try{var r=await api('fic_drafts',{});E('ficBody').innerHTML=r.drafts.length?'<div class="ficDraftList">'+r.drafts.map(function(d){return '<button type="button" data-draft="'+esc(d.id)+'"><strong>'+esc((d.number||d.document.number||'Bozza')+d.document.numeration)+'</strong><span>'+esc(d.document.entity.name)+'</span><span>'+money(d.totals.amount_gross)+' · '+esc(labels[d.state]||d.state)+'</span></button>'}).join('')+'</div>':'Nessuna bozza o fattura creata da Optyker.';E('ficBody').querySelectorAll('[data-draft]').forEach(function(b){b.onclick=function(){preview(r.drafts.find(function(d){return d.id===b.dataset.draft}),false)}})}catch(e){error(e)}}
 window.OptykerInvoices={open:function(options){api=options.call;changed=options.onChanged||function(){};if(modal)modal.remove();if(!E('ficComposerCss')){var css=document.createElement('link');css.id='ficComposerCss';css.rel='stylesheet';css.href='/billing-compose.css?v=20260909-1';document.head.appendChild(css)}modal=document.createElement('div');modal.className='ficOverlay';document.body.appendChild(modal);loadForm()}};
})();
