(function(){
if(window.__optykerEyewearFlowV9)return;
window.__optykerEyewearFlowV9=true;
window.OPTYKER_EYEWEAR_FLOW_V9_BUILD='20260906-eyewear-flow9';

var API='https://whgziwaegjzqsgcntesr.supabase.co/functions/v1/optyker-eyewear-api-v4';
var S={active:'OD',od:{},os:{},busy:false};
function E(id){return document.getElementById(id)}
function txt(v){return String(v==null?'':v).trim()}
function low(v){return txt(v).toLocaleLowerCase('it-IT')}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function euro(v){try{return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0))}catch(e){return Number(v||0).toFixed(2)+' €'}}
function num(v){var n=Number(v||0);return isFinite(n)?Math.round(n*100)/100:0}
function val(id){return E(id)?E(id).value:''}
function isClient(v){return low(v)==='del cliente'}
function isRx(v){var x=low(v);return !!x&&!isClient(x)&&!/neutra|sole/.test(x)}
function isProg(v){return /progressiv|supporto\s+accomod/.test(low(v))}
function isMono(v){return /monofocal/.test(low(v))}
function creds(){var c=window.OPTYKER_CLOUD||{};return {username:txt(c.username||window.OPTYKER_ACTIVE_USER||''),password:String(c.password||'')}}
function toast(m,t){var x=E('eyToast');if(!x){x=document.createElement('div');x.id='eyToast';x.className='eyToast';document.body.appendChild(x)}x.className='eyToast '+(t||'');x.textContent=m;x.style.display='block';clearTimeout(x.__tm);x.__tm=setTimeout(function(){x.style.display='none'},4200)}
function api(action,payload){var c=creds();if(!c.username||!c.password)return Promise.reject(new Error('Sessione operatore non disponibile.'));return fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action,username:c.username,password:c.password,payload:payload||{}})}).then(function(r){return r.json().catch(function(){return {}}).then(function(x){if(!r.ok||!x||x.ok===false)throw new Error(x&&x.error||('HTTP '+r.status));return x})})}
function sideObj(side){return side==='OS'?S.os:S.od}
function sideType(side){return txt(side==='OS'?val('eyLensTypeOS'):val('eyLensType'))}
function commonData(){return {brand:txt(val('eyLensBrand')),name:txt(val('eyLensName')),design:txt(val('eyLensDesign')),material:txt(val('eyLensMaterial')),price:num(val('eyLensPrice'))}}
function saveVisibleSide(){var o=sideObj(S.active),d=commonData();o.brand=d.brand;o.name=d.name;o.design=d.design;o.material=d.material;o.price=isClient(sideType(S.active))?0:d.price;o.type=sideType(S.active)}
function loadSide(side){var o=sideObj(side),type=sideType(side);if(E('eyLensBrand'))E('eyLensBrand').value=o.brand||'';if(E('eyLensName'))E('eyLensName').value=o.name||'';if(E('eyLensDesign'))E('eyLensDesign').value=o.design||'';if(E('eyLensMaterial'))E('eyLensMaterial').value=o.material||'';if(E('eyLensPrice')){E('eyLensPrice').value=isClient(type)?'0':(o.price!=null&&o.price!==''?Number(o.price).toFixed(2):'');E('eyLensPrice').readOnly=isClient(type)};updateChooser();renderSummary()}
function chooseSide(side){saveVisibleSide();if(side==='OS'&&!sideType('OD')){toast('Compila prima la lente DX.','error');return}S.active=side;loadSide(side)}
function lensLabel(side){var o=sideObj(side),type=sideType(side);if(isClient(type))return 'Del cliente';var bits=[type,o.brand,o.name].filter(Boolean);return bits.length?bits.join(' · '):'Da scegliere'}
function ensureChooser(){var dx=E('eyLensType'),os=E('eyLensTypeOS');if(!dx||!os||E('eyLensSideChooser'))return;var stage=dx.closest('[data-ey-stage="2"]')||dx.closest('.eyStage');if(!stage)return;var chooser=document.createElement('div');chooser.id='eyLensSideChooser';chooser.className='eyLensSideChooser';chooser.innerHTML='<div class="eyLensSideCard active" id="eyLensCardOD"><button type="button" id="eyChooseOD" class="eyLensSideBtn"><b>SCELTA DELLA LENTE DX</b><span id="eyLensSideStatusOD">Da scegliere</span></button><div id="eyLensTypeSlotOD"></div></div><div class="eyLensSideCard" id="eyLensCardOS"><button type="button" id="eyChooseOS" class="eyLensSideBtn"><b>SCELTA DELLA LENTE SX</b><span id="eyLensSideStatusOS">Compila prima DX</span></button><div id="eyLensTypeSlotOS"></div></div>';
var cat=stage.querySelector('.eyCatalogBox');if(cat)stage.insertBefore(chooser,cat);else stage.insertBefore(chooser,stage.firstChild);
var dxw=dx.closest('.eyField'),osw=os.closest('.eyField');if(dxw)E('eyLensTypeSlotOD').appendChild(dxw);if(osw)E('eyLensTypeSlotOS').appendChild(osw);
var l1=dxw&&dxw.querySelector('label'),l2=osw&&osw.querySelector('label');if(l1)l1.textContent='Tipo lente DX';if(l2)l2.textContent='Tipo lente SX';
E('eyChooseOD').onclick=function(){chooseSide('OD')};E('eyChooseOS').onclick=function(){chooseSide('OS')};
}
function updateChooser(){var od=sideType('OD'),os=sideType('OS'),b=E('eyChooseOS');if(b)b.disabled=!od;if(E('eyLensSideStatusOD'))E('eyLensSideStatusOD').textContent=lensLabel('OD');if(E('eyLensSideStatusOS'))E('eyLensSideStatusOS').textContent=od?lensLabel('OS'):'Compila prima DX';if(E('eyLensCardOD'))E('eyLensCardOD').classList.toggle('active',S.active==='OD');if(E('eyLensCardOS'))E('eyLensCardOS').classList.toggle('active',S.active==='OS')}
function treatments(){var p=E('eyewearPanel')||document;return Array.prototype.slice.call(p.querySelectorAll('[data-ey-treatment]:checked')).map(function(x){return x.value})}
function ensureTreatmentUI(){var p=E('eyewearPanel');if(!p)return;['Idrofobico / oleofobico','Antigraffio'].forEach(function(v){var x=p.querySelector('[data-ey-treatment][value="'+v+'"]');var lab=x&&x.closest('label');if(lab)lab.remove()});var labels={'Indurente':['Indurente','€ 10 a lente'],'Antiriflesso':['Antiriflesso','€ 15 a lente'],'Antiriflesso premium':['Antiriflesso premium','Solo lenti di ricetta · € 25 progressive / € 20 altre'],'Filtro luce blu':['Luce blu','€ 25 a lente'],'Polarizzato':['Polarizzato','Solo lenti di ricetta · € 20 a lente'],'UV':['Protezione U.V.','€ 5 a lente'],'Precal':['Precal','€ 25 a lente'],'Personalizzazione':['Personalizzazione','In omaggio']};Object.keys(labels).forEach(function(v){var x=p.querySelector('[data-ey-treatment][value="'+v+'"]'),lab=x&&x.closest('label');if(!lab)return;var sp=lab.querySelector('span');if(!sp){sp=document.createElement('span');lab.appendChild(sp)}sp.innerHTML=esc(labels[v][0])+'<small>'+esc(labels[v][1])+'</small>'});var hasRx=[sideType('OD'),sideType('OS')].some(isRx);['Antiriflesso premium','Polarizzato'].forEach(function(v){var x=p.querySelector('[data-ey-treatment][value="'+v+'"]');if(!x)return;x.disabled=!hasRx;if(!hasRx)x.checked=false;var lab=x.closest('label');if(lab)lab.classList.toggle('disabled',!hasRx)})}
function supplied(){return ['OD','OS'].filter(function(s){var t=sideType(s);return !!t&&!isClient(t)})}
function sidePrice(side){var o=sideObj(side);if(S.active===side&&!isClient(sideType(side)))o.price=num(val('eyLensPrice'));return isClient(sideType(side))?0:num(o.price)}
function treatmentDetails(){var sold=supplied(),out=[];treatments().forEach(function(tr){var unit=0,total=0,count=0,free=false;if(tr==='Indurente'){unit=10;count=sold.length;total=unit*count}else if(tr==='Antiriflesso'){unit=15;count=sold.length;total=unit*count}else if(tr==='Filtro luce blu'){unit=25;count=sold.length;total=unit*count}else if(tr==='UV'){unit=5;count=sold.length;total=unit*count}else if(tr==='Precal'){unit=25;count=sold.length;total=unit*count}else if(tr==='Personalizzazione'){free=true;count=sold.length}else if(tr==='Polarizzato'){unit=20;count=sold.filter(function(s){return isRx(sideType(s))}).length;total=unit*count}else if(tr==='Antiriflesso premium'){sold.forEach(function(s){var t=sideType(s);if(isRx(t)){count++;total+=isProg(t)?25:20}})}out.push({name:tr,unit:unit,count:count,total:num(total),free:free})});return out}
function colorInfo(){var x=(E('eyewearPanel')||document).querySelector('[data-ey-color].active'),m=low(x&&x.getAttribute('data-ey-color')),unit=/photo|foto/.test(m)?40:/sun|sole/.test(m)?20:0,count=supplied().length;return {mode:m,unit:unit,count:count,total:unit*count,label:unit===40?'Fotocromatico':unit===20?'Sole':''}}
function indexInfo(){var v=txt(val('eyLensIndexChoice')||'1.5'),unit=v==='1.6'?10:v==='1.67'?20:v==='1.74'?30:0,count=supplied().length;return {value:v,label:v==='1.5'?'1.50':v,unit:unit,count:count,total:unit*count}}
function geometryInfo(){var v=txt(val('eyLensGeometry')||'sferica'),unit=v==='asferica'?10:v==='bi_asferica'?20:0,count=supplied().filter(function(s){return isMono(sideType(s))}).length;return {value:v,label:v==='asferica'?'Asferica':v==='bi_asferica'?'Bi-asferica':'Sferica',unit:unit,count:count,total:unit*count}}
function warrantyInfo(){var w=txt(val('eyWarranty')||'Base'),p=w==='Silver'?20:w==='Gold'?100:0;return {name:w,total:p}}
function mountingInfo(){var m=txt(val('eyMounting')),p=0,label='';if(m==='special'){p=25;label='Montaggio speciale'}else if(m==='traditional'){p=supplied().some(function(s){return isProg(sideType(s))})?25:15;label='Montaggio tradizionale'}return {mode:m,label:label,total:p}}
function pricing(){saveVisibleSide();var frame=isClient(val('eyFrameType'))?0:num(val('eyFramePrice')),od=sidePrice('OD'),os=sidePrice('OS'),gross=num(od+os),discount=Math.max(0,Math.min(100,Number(val('eyDiscount')||0))),disc=num(gross*discount/100),net=num(gross-disc),td=treatmentDetails(),tt=num(td.reduce(function(a,x){return a+x.total},0)),ci=colorInfo(),ii=indexInfo(),gi=geometryInfo(),wi=warrantyInfo(),mi=mountingInfo(),total=num(frame+net+tt+ci.total+ii.total+gi.total+wi.total+mi.total);return {frame:frame,od:od,os:os,gross:gross,discount:discount,disc:disc,net:net,treatments:td,treatmentTotal:tt,color:ci,index:ii,geometry:gi,warranty:wi,mounting:mi,total:total}}
function renderSummary(){var box=E('eySummary');if(!box)return;var p=pricing(),od=sideType('OD'),os=sideType('OS');var extras=p.treatments.map(function(x){return '<div class="eySummaryRow"><span>'+esc(x.name)+(x.count?' · '+x.count+' lente'+(x.count===1?'':'i'):'')+'</span><b>'+(x.free?'In omaggio':esc(euro(x.total)))+'</b></div>'}).join('');var color=p.color.label?'<div class="eySummaryRow"><span>'+esc(p.color.label)+' · '+p.color.count+' lente'+(p.color.count===1?'':'i')+'</span><b>'+esc(euro(p.color.total))+'</b></div>':'';var geo=p.geometry.count?'<div class="eySummaryRow"><span>Geometria '+esc(p.geometry.label)+' · '+p.geometry.count+' lente'+(p.geometry.count===1?'':'i')+'</span><b>'+esc(euro(p.geometry.total))+'</b></div>':'';box.innerHTML='<div class="eySummaryRow"><span>Montatura</span><b>'+esc(euro(p.frame))+'</b></div><div class="eySummaryRow"><span>Lente DX · '+esc(od||'—')+'</span><b>'+esc(euro(p.od))+'</b></div><div class="eySummaryRow"><span>Lente SX · '+esc(os||'—')+'</span><b>'+esc(euro(p.os))+'</b></div><div class="eySummaryRow"><span>Totale lenti</span><b>'+esc(euro(p.gross))+'</b></div>'+(p.discount?'<div class="eySummaryRow discount"><span>Sconto lenti '+p.discount+'%</span><b>− '+esc(euro(p.disc))+'</b></div>':'')+'<div class="eySummaryRow"><span>Indice '+esc(p.index.label)+' · '+p.index.count+' lente'+(p.index.count===1?'':'i')+'</span><b>'+esc(euro(p.index.total))+'</b></div>'+geo+'<div class="eySummaryRow"><span>Garanzia '+esc(p.warranty.name)+'</span><b>'+(p.warranty.total?esc(euro(p.warranty.total)):'Inclusa')+'</b></div>'+extras+color+(p.mounting.label?'<div class="eySummaryRow"><span>'+esc(p.mounting.label)+'</span><b>'+esc(euro(p.mounting.total))+'</b></div>':'')+'<div class="eySummaryRow total"><span>Totale</span><b>'+esc(euro(p.total))+'</b></div>'}
function framePayload(p){var client=isClient(val('eyFrameType'));return {brand:client?'':txt(val('eyFrameBrand')),model:client?'':txt(val('eyFrameModel')),type:txt(val('eyFrameType')),color:client?'':txt(val('eyFrameColor')),description:client?'':txt(val('eyFrameDescription')),price:client?0:p.frame,barcode:client?'':txt(val('eyFrameBarcode')),sku:client?'':txt(val('eyFrameSku'))}}
function lensSidePayload(side){var o=sideObj(side),t=sideType(side),client=isClient(t);return {side:side,type:t,brand:client?'':txt(o.brand),lens_name:client?'':txt(o.name),design:client?'':txt(o.design),material:client?'':txt(o.material),unit_price:client?0:sidePrice(side),client_owned:client}}
function payload(){var p=pricing(),od=lensSidePayload('OD'),os=lensSidePayload('OS'),qty=supplied().length,avg=qty?p.gross/qty:0,cm=p.color.mode;return {mode:E('eyModeJob')&&E('eyModeJob').classList.contains('active')?'job':'quote',client_id:txt(val('eyClient')),frame:framePayload(p),lens:{lens_type:od.type===os.type?od.type:('DX: '+od.type+' / SX: '+os.type),lens_type_od:od.type,lens_type_os:os.type,lens_od:od,lens_os:os,brand:od.brand===os.brand?od.brand:[od.brand,os.brand].filter(Boolean).join(' / '),lens_name:od.lens_name===os.lens_name?od.lens_name:[od.lens_name,os.lens_name].filter(Boolean).join(' / '),design:od.design===os.design?od.design:[od.design,os.design].filter(Boolean).join(' / '),material:od.material===os.material?od.material:[od.material,os.material].filter(Boolean).join(' / '),refractive_index:txt(val('eyLensIndexChoice')||'1.5'),geometry:txt(val('eyLensGeometry')||'sferica'),treatments:treatments(),mounting:txt(val('eyMounting')),color_mode:cm,color:/clear/.test(cm)?'':txt(val('eyLensColor')),polarized:treatments().indexOf('Polarizzato')>=0,photochromic:/photo|foto/.test(cm),quantity:qty,unit_price:num(avg),unit_price_od:od.unit_price,unit_price_os:os.unit_price},warranty:txt(val('eyWarranty')||'Base'),discount_percent:p.discount,pricing_client:p,notes:txt(val('eyNotes'))}}
function validate(){var fp=framePayload(pricing()),ft=txt(fp.type);if(!ft){toast('Seleziona il tipo montatura.','error');return false}if(!isClient(ft)&&!txt(fp.brand||fp.model||fp.description)){toast('Inserisci o seleziona la montatura.','error');return false}var od=sideType('OD'),os=sideType('OS');if(!od){toast('Seleziona prima la lente DX.','error');chooseSide('OD');return false}if(!os){toast('Seleziona la lente SX.','error');chooseSide('OS');return false}var tr=treatments();if((tr.indexOf('Antiriflesso premium')>=0||tr.indexOf('Polarizzato')>=0)&&![od,os].some(isRx)){toast('Antiriflesso premium e Polarizzato sono disponibili solo sulle lenti di ricetta.','error');return false}return true}
function save(btn){if(S.busy||!validate())return;S.busy=true;var old=btn.textContent;btn.disabled=true;btn.textContent='Salvataggio…';api('save',payload()).then(function(x){var r=x.data||{};if(E('eyReference'))E('eyReference').value=r.reference_code||r.reference_no||'';toast((payload().mode==='quote'?'Preventivo':'Busta')+' salvato'+(r.reference_code?' · '+r.reference_code:''),'ok')}).catch(function(e){toast('Salvataggio non riuscito: '+e.message,'error')}).finally(function(){S.busy=false;btn.disabled=false;btn.textContent=old})}
function printSheet(){if(!validate())return;var d=payload(),p=d.pricing_client,w=window.open('','_blank','width=860,height=980');if(!w){toast('Il browser ha bloccato la finestra di stampa.','error');return}w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Scheda Occhiali</title><style>body{font-family:Arial,sans-serif;color:#17334b;padding:30px}h1{font-size:24px}h2{font-size:15px;margin-top:24px;border-bottom:1px solid #ccd8e1;padding-bottom:6px}table{width:100%;border-collapse:collapse}td{padding:7px;border-bottom:1px solid #e7edf1}td:last-child{text-align:right;font-weight:700}.total{font-size:18px;font-weight:900}</style></head><body><h1>Scheda Occhiali</h1><h2>Montatura</h2><table><tr><td>Tipo</td><td>'+esc(d.frame.type||'—')+'</td></tr><tr><td>Marca</td><td>'+esc(d.frame.brand||'Del cliente')+'</td></tr><tr><td>Prezzo</td><td>'+esc(euro(p.frame))+'</td></tr></table><h2>Lenti</h2><table><tr><td>DX</td><td>'+esc(lensLabel('OD'))+' · '+esc(euro(p.od))+'</td></tr><tr><td>SX</td><td>'+esc(lensLabel('OS'))+' · '+esc(euro(p.os))+'</td></tr><tr><td>Trattamenti</td><td>'+esc(d.lens.treatments.join(', ')||'—')+'</td></tr><tr><td>Montaggio</td><td>'+esc(p.mounting.label||'—')+'</td></tr><tr class="total"><td>TOTALE</td><td>'+esc(euro(p.total))+'</td></tr></table></body></html>');w.document.close();setTimeout(function(){try{w.focus();w.print()}catch(e){}},250)}
function catalogSelected(){var target=S.active,dxBefore=sideType('OD');setTimeout(function(){var selected={type:txt(val('eyLensType')),brand:txt(val('eyLensBrand')),name:txt(val('eyLensName')),design:txt(val('eyLensDesign')),material:txt(val('eyLensMaterial')),price:num(val('eyLensPrice'))};var o=sideObj(target);Object.keys(selected).forEach(function(k){o[k]=selected[k]});if(target==='OS'){if(E('eyLensTypeOS'))E('eyLensTypeOS').value=selected.type;if(E('eyLensType'))E('eyLensType').value=S.od.type||dxBefore;S.os.type=selected.type}else{S.od.type=selected.type}loadSide(target);ensureTreatmentUI();updateChooser();renderSummary()},120)}
function ensureStyle(){if(E('eyFlowV9Css'))return;var st=document.createElement('style');st.id='eyFlowV9Css';st.textContent='.eyLensSideChooser{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0 12px}.eyLensSideCard{border:1px solid #d7e3eb;border-radius:11px;background:#f8fbfd;padding:10px}.eyLensSideCard.active{border-color:#1769aa;box-shadow:0 0 0 2px rgba(23,105,170,.08)}.eyLensSideBtn{width:100%;min-height:54px;border:1px solid #bfd4e3;border-radius:9px;background:#fff;color:#244b68;text-align:left;padding:9px 11px;cursor:pointer}.eyLensSideBtn b{display:block;font-size:10px}.eyLensSideBtn span{display:block;font-size:8px;color:#748897;margin-top:3px}.eyLensSideCard.active .eyLensSideBtn{background:#1769aa;border-color:#1769aa;color:#fff}.eyLensSideCard.active .eyLensSideBtn span{color:#eaf5fc}.eyLensSideBtn:disabled{opacity:.45;cursor:not-allowed}.eyLensSideCard .eyField{margin-top:9px}.eyCheck.disabled{opacity:.42}.eyCheck span{display:flex;flex-direction:column;gap:2px}.eyCheck small{font-size:7px;color:#758999}@media(max-width:700px){.eyLensSideChooser{grid-template-columns:1fr}}';document.head.appendChild(st)}
function ensure(){var p=E('eyewearPanel');if(!p)return false;ensureChooser();ensureStyle();ensureTreatmentUI();if(E('eyFrameBrand'))E('eyFrameBrand').placeholder='Es. Michael Optyker';var ft=E('eyFrameType');if(ft&&!Array.prototype.some.call(ft.options,function(o){return txt(o.value||o.textContent)==='Del cliente'})){var op=document.createElement('option');op.textContent='Del cliente';op.value='Del cliente';ft.appendChild(op)}updateChooser();return true}
window.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('button,.eyLensRow'):null;if(!b)return;if(b.classList&&b.classList.contains('eyLensRow')){catalogSelected();return}if(b.id==='eyCatalogGo'&&S.active==='OS'){var dx=E('eyLensType'),before=dx&&dx.value;if(dx)dx.value=sideType('OS');setTimeout(function(){if(dx)dx.value=S.od.type||before||''},0);return}if(b.id==='eySave'){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();save(b);return}if(b.id==='eyPrint'||(/stampa/i.test(txt(b.textContent))&&E('eyewearPanel')&&E('eyewearPanel').contains(b))){ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();printSheet();return}},true);
document.addEventListener('change',function(ev){if(!E('eyewearPanel')||!E('eyewearPanel').contains(ev.target))return;if(ev.target===E('eyLensType')){S.od.type=sideType('OD');if(isClient(S.od.type)){S.od={type:S.od.type,price:0};if(S.active==='OD')loadSide('OD')}updateChooser()}else if(ev.target===E('eyLensTypeOS')){S.os.type=sideType('OS');if(isClient(S.os.type)){S.os={type:S.os.type,price:0};if(S.active==='OS')loadSide('OS')}updateChooser()}ensureTreatmentUI();setTimeout(renderSummary,140)},true);
document.addEventListener('input',function(ev){if(!E('eyewearPanel')||!E('eyewearPanel').contains(ev.target))return;if(['eyLensBrand','eyLensName','eyLensDesign','eyLensMaterial','eyLensPrice'].indexOf(ev.target.id)>=0)saveVisibleSide();setTimeout(renderSummary,140)},true);
document.addEventListener('click',function(ev){var r=ev.target&&ev.target.closest?ev.target.closest('#eyReset'):null;if(r)setTimeout(function(){S.active='OD';S.od={};S.os={};loadSide('OD');updateChooser()},80)},true);
function boot(){if(!ensure()){setTimeout(boot,200);return}S.od.type=sideType('OD');S.os.type=sideType('OS');if(!S.od.price&&S.active==='OD')saveVisibleSide();loadSide('OD');setInterval(function(){if(E('eyewearPanel')){ensureTreatmentUI();updateChooser();renderSummary()}},650)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
