import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {webcrypto} from 'node:crypto';
import * as domain from '../supabase/functions/optyker-fiscal-api-v2/reissue-domain.mjs';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
function fixture(){
 const sale={id:id(1),client_id:id(2),status:'completed',total:450,paid_amount:450,due_amount:0,data:{fiscal_reissue_pending:true}};
 const pays=[250,200].map((amount,i)=>({id:id(10+i),sale_id:sale.id,client_id:sale.client_id,amount,payment_method:'card'}));
 const root=pays.map((p,i)=>({id:id(20+i),sale_id:sale.id,payment_id:p.id,operation:'sale',state:'completed',serial:'FIXTURE',document_number:'1111-000'+(i+1),document_date:'2026-09-20',document:{totalCents:p.amount*100,lines:[{department:1,quantity:1,unitPriceCents:p.amount*100,description:'ACCONTO OCCHIALE',expenseCode:'none'}]}}));
 const voids=root.map((p,i)=>({...p,id:id(30+i),operation:'void',original_job_id:p.id,document_number:'1112-000'+(i+1),document_date:'2026-09-23'}));
 return {optyker_pos_sales:[sale],optyker_pos_payments:pays,optyker_fiscal_jobs:[...root,...voids]};
}
function boot(tables){let handler;const writes=[];
 class Query{constructor(table){this.table=table;this.filters=[];this.singleRow=false;this.patch=null;}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}in(k,vs){this.filters.push([k,vs]);return this;}limit(){return this;}single(){this.singleRow=true;return this;}maybeSingle(){this.singleRow=true;return this;}insert(p){this.patch=p;this.kind='insert';return this;}update(p){this.patch=p;this.kind='update';return this;}then(resolve){let rows=(tables[this.table]||[]).filter(r=>this.filters.every(([k,v])=>{const value=k.includes('->>')?String(r[k.split('->>')[0]]?.[k.split('->>')[1]]):r[k];return Array.isArray(v)?v.includes(value):value===v;}));if(this.patch){writes.push({table:this.table,kind:this.kind,patch:this.patch});if(this.kind==='insert'){rows=[this.patch];tables[this.table].push(this.patch);}else rows=rows.map(r=>Object.assign(r,this.patch));}return Promise.resolve({data:this.singleRow?(rows[0]||null):rows,error:null}).then(resolve);}}
 const db={from:t=>new Query(t),rpc:async(name,args)=>({data:{ok:args.p_password==='fixture-password',username:'FIXTURE'},error:null})};
 const context={...domain,createClient:()=>db,makeDocument:(p,i)=>({serial:'FIXTURE',operation:'sale',totalCents:Math.round(p.amount*100),lines:i.lines,commands:['FIXTURE ONLY']}),markAutomaticDocument:(d,jobId)=>({...d,referenceReadback:{jobId}}),Deno:{env:{get:()=>''}},crypto:webcrypto,TextEncoder,Response,Set,Map,Date,JSON,Error,console};
 const code=fs.readFileSync(new URL('../supabase/functions/optyker-fiscal-api-v2/reissue.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');vm.runInNewContext(code.replace(/^export /gm,''),context);handler=async request=>{try{return new Response(JSON.stringify(await context.handleReceiptReissue(await request.json())),{status:200})}catch(e){return new Response(JSON.stringify({ok:false,error:e.message}),{status:e.message==='AUTH_REQUIRED'?401:400})}};return {call:b=>handler(new Request('https://fixture.invalid',{method:'POST',headers:{Origin:'https://www.optyker.it'},body:JSON.stringify(b)})),writes};
}
test('anonymous requests are denied with no database mutation',async()=>{const {call,writes}=boot(fixture());const r=await call({action:'reissue_status',payload:{client_id:id(2)}});assert.equal(r.status,401);assert.equal(writes.length,0)});
test('authenticated status reports both paid receipts ready and writes nothing',async()=>{const {call,writes}=boot(fixture());const r=await call({username:'staff',password:'fixture-password',action:'reissue_status',payload:{client_id:id(2)}});const b=await r.json();assert.equal(r.status,200);assert.equal(b.data.sales[0].remaining_cents,45000);assert.equal(writes.length,0)});
test('prepare refuses a different customer',async()=>{const {call,writes}=boot(fixture());const r=await call({username:'staff',password:'fixture-password',action:'reissue_prepare',payload:{sale_id:id(1),client_id:id(99),payment_id:id(10),original_job_id:id(20),void_job_id:id(30),confirm_not_already_reissued:true}});assert.equal(r.status,400);assert.equal(writes.length,0)});
test('prepare creates only one prepared job with the original payment, no printer call',async()=>{const {call,writes}=boot(fixture());const r=await call({username:'staff',password:'fixture-password',action:'reissue_prepare',payload:{sale_id:id(1),client_id:id(2),payment_id:id(10),original_job_id:id(20),void_job_id:id(30),confirm_not_already_reissued:true}});const b=await r.json();assert.equal(r.status,200,JSON.stringify(b));assert.match(b.data.claim_token,/^[a-f0-9]{64}$/);assert.equal(writes.length,1);assert.equal(writes[0].table,'optyker_fiscal_jobs');assert.equal(writes[0].patch.state,'prepared');assert.equal(writes[0].patch.payment_id,id(10));assert.equal(writes[0].patch.reissue_of_job_id,id(20));assert.equal(writes[0].patch.document.totalCents,25000)});
test('an already emitted replacement cannot be prepared again',async()=>{const t=fixture();t.optyker_fiscal_jobs.push({...t.optyker_fiscal_jobs[0],id:id(40),reissue_of_job_id:id(20),state:'awaiting_reference',document_number:null});const {call,writes}=boot(t);const r=await call({username:'staff',password:'fixture-password',action:'reissue_prepare',payload:{sale_id:id(1),client_id:id(2),payment_id:id(10),original_job_id:id(20),void_job_id:id(30),confirm_not_already_reissued:true}});const b=await r.json();assert.equal(r.status,200);assert.equal(b.data.claim_token,undefined);assert.equal(writes.length,0)});
