import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../cash-fiscal-reissue.js',import.meta.url),'utf8');
function boot({confirm=true,state='ready',outcome='completed',outcomes=null}={}){
 const calls=[],nodes={},plans=[{sale_id:'SALE',remaining_cents:45000,complete:false,payments:[{payment_id:'P1',original_job_id:'O1',void_job_id:'V1',amount_cents:25000,state},{payment_id:'P2',original_job_id:'O2',void_job_id:'V2',amount_cents:20000,state:'ready'}]}];let snapshots={groups:[],conflicts:[],blockers:[],receipt_reissues:plans},finished=false,jobPolls=0;
 function elem(){return {id:'',dataset:{},innerHTML:'',textContent:'',hidden:false,disabled:false,setAttribute(){},appendChild(n){nodes[n.id]=n},querySelectorAll(){return []}}}
 nodes.optykerCashCheckoutBtn=elem();const head=elem();
 const ctx={window:{optykerCashReloadClientCart:async()=>calls.push({action:'reload'})},document:{querySelector:()=>head,createElement:()=>elem()},E:id=>nodes[id],S:{clientId:'CLIENT',busy:false,cashOpen:true},recordedBalance:{requested:''},balanceFetch:async()=>snapshots,balanceData:()=>snapshots,balancePaint(){},balanceLoad:async()=>{snapshots.receipt_reissues=finished?[]:plans},cartRows:()=>[],checkout:()=>calls.push({action:'checkout'}),balanceOpenReceipt(){},creds:()=>({username:'fixture',password:'fixture-password'}),esc:String,euro:n=>n.toFixed(2)+' EUR',clientCartQueue:Promise.resolve(),clientCartSaveTimer:0,AbortController,setTimeout,clearTimeout,Date,console,confirm:()=>confirm,
 fetch:async(url,init)=>{const b=JSON.parse(init.body);calls.push(b);let data;if(b.action==='reissue_status')data={sales:plans};else if(b.action==='status')data={online:true,status:{ok:true,mode:'REG',idleState:0,busy:0,errorCode:0,printerError:0,paperEnd:0,coverOpen:0}};else if(b.action==='reissue_prepare')data={job:{id:'J'+b.payload.payment_id,state:'prepared'},claim_token:'mock-capability'};else if(b.action==='queue_fiscal')data={id:'COMMAND'};else if(b.action==='job')data={job:{id:b.payload.job_id,state:outcomes?(outcomes[jobPolls++]||outcome):outcome}};else if(b.action==='reissue_finish'){finished=true;data={completed:true}}else throw new Error('UNEXPECTED ACTION '+b.action);return {ok:true,json:async()=>({ok:true,data})}}};
 vm.createContext(ctx);vm.runInContext(source,ctx);return {ctx,calls,nodes};
}
test('renders dedicated reissue and blocks new collection',()=>{const {ctx,nodes,calls}=boot();ctx.balancePaint();assert.match(nodes.optykerReceiptReissuePanel.innerHTML,/Riemetti scontrini/);assert.equal(nodes.optykerCashCheckoutBtn.disabled,true);ctx.checkout();assert.equal(calls.length,0)});
test('cancelled confirmation never dispatches a document',async()=>{const {ctx,calls}=boot({confirm:false});await ctx.runReceiptReissue('SALE');assert.equal(calls.some(c=>c.action==='queue_fiscal'),false);assert.equal(ctx.S.busy,false)});
test('two replacements use original payments and no checkout/settle',async()=>{const {ctx,calls}=boot();await ctx.runReceiptReissue('SALE');assert.deepEqual(calls.filter(c=>c.action==='reissue_prepare').map(c=>c.payload.payment_id),['P1','P2']);assert.equal(calls.filter(c=>c.action==='queue_fiscal').length,2);assert.equal(calls.some(c=>['checkout','settle'].includes(c.action)),false);assert.equal(calls.some(c=>c.action==='reissue_finish'),true);assert.equal(ctx.S.busy,false)});
test('uncertain prior outcome never dispatches again',async()=>{const {ctx,calls}=boot({state:'uncertain'});await ctx.runReceiptReissue('SALE');assert.equal(calls.some(c=>c.action==='queue_fiscal'),false);assert.match(ctx.receiptReissue.message,/non ripetere/i)});
test('first new receipt waiting reference stops second and does not finish',async()=>{const {ctx,calls}=boot({outcome:'awaiting_reference'});await ctx.runReceiptReissue('SALE');assert.equal(calls.filter(c=>c.action==='queue_fiscal').length,1);assert.equal(calls.some(c=>c.action==='reissue_finish'),false);assert.match(ctx.receiptReissue.message,/Verifica riferimenti/)});
test('preflight with zero commands retries once, preserving original payments',async()=>{const {ctx,calls}=boot({outcomes:['not_started','completed','completed']});await ctx.runReceiptReissue('SALE');assert.deepEqual(calls.filter(c=>c.action==='reissue_prepare').map(c=>c.payload.payment_id),['P1','P1','P2']);assert.equal(calls.filter(c=>c.action==='queue_fiscal').length,3);assert.equal(calls.some(c=>c.action==='reissue_finish'),true);assert.equal(calls.some(c=>['checkout','settle'].includes(c.action)),false)});
test('two preflight failures stop without a third dispatch or completion',async()=>{const {ctx,calls}=boot({outcomes:['not_started','not_started']});await ctx.runReceiptReissue('SALE');assert.equal(calls.filter(c=>c.action==='queue_fiscal').length,2);assert.equal(calls.some(c=>c.action==='reissue_finish'),false)});
