// Tests the actual SQL, handler, PDF bytes and complete UI. Never uses production data.
import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {defaults,validate,ALL_FIELDS} from '../delivery-schema.mjs';import {service} from '../supabase/functions/optyker-eyewear-delivery/service.mjs';
const require=createRequire(import.meta.url),{Client}=require('pg'),lib=require('pdf-lib'),{PNG}=require('pngjs'),{chromium}=require('playwright');
const OUT='delivery-check';fs.mkdirSync(OUT,{recursive:true});const pg=new Client({host:'localhost',user:'postgres',password:'synthetic_ci_only',database:'delivery_test'});await pg.connect();
const db={rpc:async(name,p)=>{try{const r=await pg.query('select public.'+name+'($1,$2,$3,$4) as x',[p.p_username,p.p_password,p.p_action,p.p_payload]);return {data:r.rows[0].x};}catch(e){return {error:{message:e.message}};}}};
const run=service(db,lib,PNG),base={username:'Michael Mologni',password:'SYNTHETIC_PASSWORD_NOT_REAL'},cid='11111111-1111-4111-8111-111111111111',sid='33333333-3333-4333-8333-333333333333';
const call=(action,p={})=>run({...base,action,payload:{client_id:cid,sheet_id:sid,...p}});const report={ok:false,checks:[],live:process.env.OPTYKER_LIVE==='1',production_writes:0,browser_errors:[]};let browser,page;
try{
 await assert.rejects(()=>run({...base,password:'badpass123',action:'get',payload:{client_id:cid,sheet_id:sid}}),/autorizzato/);await assert.rejects(()=>call('get',{client_id:'22222222-2222-4222-8222-222222222222'}),/Busta/);await assert.rejects(()=>call('get',{sheet_id:'44444444-4444-4444-8444-444444444444'}),/Busta/);
 assert.equal((await pg.query("select has_function_privilege('anon','optyker_delivery_internal(text,text,text,jsonb)','execute') as v")).rows[0].v,false);
 const source=await call('get');const vals=defaults(source),today=new Date().toISOString().slice(0,10);
 Object.assign(vals,{issuer_name:'FABBRICANTE DI PROVA - FACSIMILE',issuer_vat:'PIVA DIMOSTRATIVA',issuer_tax:'CF DIMOSTRATIVO',declaration_date:today,delivery_date:today,prescription_date:today,prescription_origin:'Come da prescrizione allegata',prescription_author:'Prescrittore dimostrativo',prescription_qualification:'Qualifica di prova',prescription_ref:'PRESCRIZIONE DI ESEMPIO',operator_name:'Operatore dimostrativo',operator_capacity:'Qualifica di prova',exceptions:'Nessuno - esclusivamente dati di esempio',unknown_reasons:'Eventuali campi non compilati non sono applicabili al facsimile.',technical_verified:true,conformity_confirmed:true});
 for(const pre of ['frame','od','os']){vals[pre+'_ce']='Sì - verificata';vals[pre+'_technical_file']='Fascicolo produttore - ESEMPIO';vals[pre+'_supplier']='Fornitore esempio';vals[pre+'_material']='Organico / acetato - ESEMPIO';vals[pre+'_brand']='Marca esempio';vals[pre+'_lot']='LOTTO-PROVA';}
 for(const side of ['od','os'])Object.assign(vals,{[side+'_name']:'Monofocale dimostrativa',[side+'_family']:'Monofocale',[side+'_index']:'1,60',[side+'_diameter']:'70',[side+'_filter']:'0',[side+'_color']:'Trasparente',[side+'_treatments']:'Antiriflesso',[side+'_L_sphere']:'-1,00',[side+'_L_cylinder']:'-0,50',[side+'_L_axis']:'180',[side+'_L_sdi']:'31'});
 validate(vals);assert.throws(()=>validate({...vals,delivery_date:''}),/Completa/);assert.throws(()=>validate({...vals,frame_ce:'Da verificare'}),/marcatura/);report.checks.push('Real SQL authentication, private execution, client ownership, job-only gate and required validation');
 const before=await pg.query('select data from optyker_sheets where id=$1',[sid]);let stage=await call('prepare',{values:vals,source_hash:source.source_hash,previous_archive_id:null});
 assert.equal((await pg.query('select count(*) as n from optyker_eyewear_delivery_archive')).rows[0].n,'0');
 const png=new PNG({width:900,height:200});for(let i=0;i<png.data.length;i+=4){png.data[i]=255;png.data[i+1]=255;png.data[i+2]=255;png.data[i+3]=0;}const blank='data:image/png;base64,'+PNG.sync.write(png).toString('base64');for(let x=50;x<750;x++)for(let t=0;t<4;t++){const y=90+Math.round(25*Math.sin(x/40))+t,i=(900*y+x)*4;png.data[i]=25;png.data[i+1]=40;png.data[i+2]=60;png.data[i+3]=255;}
 const sig='data:image/png;base64,'+PNG.sync.write(png).toString('base64');const req={document_id:stage.id,preview_sha256:stage.pdf_sha256,operator_signature:sig,client_signature:sig,identity_checked:true,client_accepts:true,instructions_delivered:true,confirm:true};
 await assert.rejects(()=>call('sign',{...req,client_signature:blank}),/vuota/);await assert.rejects(()=>call('sign',{...req,client_accepts:false}),/Conferma/);
 const signed=await call('sign',req),again=await call('sign',req);assert.equal(signed.pdf_sha256,again.pdf_sha256);assert.equal(signed.pdf_base64,again.pdf_base64);assert.equal(signed.revision,1);
 const archive=await call('archive',{document_id:signed.id});assert.equal(archive.pdf_base64,signed.pdf_base64);const bytes=Buffer.from(signed.pdf_base64,'base64');fs.writeFileSync(OUT+'/Optyker_consegna_firmata_ESEMPIO.pdf',bytes);assert((await lib.PDFDocument.load(bytes)).getPageCount()>=2);
 await assert.rejects(()=>pg.query('update optyker_eyewear_delivery_archive set revision=99'),/non modificabile/);await assert.rejects(()=>pg.query('delete from optyker_eyewear_delivery_archive'),/non modificabile/);
 assert.deepEqual((await pg.query('select data from optyker_sheets where id=$1',[sid])).rows,before.rows);report.checks.push('Server-generated signed PDF persisted byte-for-byte; same-file reprint; missing signatures and consent blocked; retry idempotent; archive immutable; busta unchanged');
 await assert.rejects(()=>call('prepare',{values:vals,source_hash:source.source_hash,previous_archive_id:null}),/revisione/);
 const source2=await call('get'),stale=await call('prepare',{values:vals,source_hash:source2.source_hash,previous_archive_id:source2.previous_archive_id});await pg.query('update optyker_sheets set updated_at=now() where id=$1',[sid]);await assert.rejects(()=>call('sign',{...req,document_id:stale.id,preview_sha256:stale.pdf_sha256}),/cambiati/);report.checks.push('Stale source and conflicting revisions rejected before signing');
 // Complete published interface with business calls routed to disposable real SQL + real server handler.
 browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:1440,height:1050},serviceWorkers:'block'});page=await ctx.newPage();page.setDefaultTimeout(12000);page.on('dialog',d=>d.accept());
 page.on('pageerror',e=>report.browser_errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.browser_errors.push(m.text());});
 const clients=[{id:cid,name:'Cliente',surname:'Dimostrativo'}];
 const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'content-type,authorization,apikey,x-client-info','Cache-Control':'no-store'};
 await ctx.route('**/*',async route=>{const q=route.request(),u=new URL(q.url());let b={};try{b=q.postDataJSON()||{};}catch{}
  if(u.pathname.includes('/rest/v1/')||u.pathname.includes('/functions/v1/')||q.method()!=='GET'){
   if(q.method()==='OPTIONS')return route.fulfill({status:204,headers:cors,body:''});
   let x={ok:true,data:[],rows:[],clients:[],sheets:[],orders:[],messages:[]},status=200;
   if(u.pathname.endsWith('/optyker-eyewear-delivery')){try{x=await run(b);}catch(e){x={ok:false,error:e.message};status=400;}}
   else if(u.pathname.includes('optyker-staff-auth'))x={ok:true,username:b.username,needs_password:false,has_email:true};
   else if(u.pathname.endsWith('/optyker_client_sheet_actions'))x={ok:true,data:[(await call('get')).sheet]};
   else if(u.pathname.endsWith('/optyker_api')){if(b.p_action==='list_clients')x={ok:true,data:clients};if(b.p_action==='list_sheets')x={ok:true,data:[(await call('get')).sheet]};}
   else if(u.pathname.endsWith('/optyker_ovc_api'))x={ok:true,data:{client_id:cid,active:true,card_number:1,revision:1}};
   return route.fulfill({status,headers:cors,contentType:'application/json',body:JSON.stringify(x)});
  }
  if(!report.live&&['www.optyker.it','optyker.it'].includes(u.hostname)){let rel=u.pathname.replace(/^\//,'');if(!rel||rel.endsWith('/'))rel+='index.html';const p=path.resolve('_site',rel);if(p.startsWith(path.resolve('_site')+path.sep)&&fs.existsSync(p)&&fs.statSync(p).isFile())return route.fulfill({contentType:({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml','.json':'application/json'}[path.extname(p)]||'application/octet-stream'),body:fs.readFileSync(p)});}
  return route.continue();
 });
 await page.goto('https://www.optyker.it/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.OPTYKER_EYEWEAR_DELIVERY?.version==='20260911-delivery1');const op=await page.locator('#optykerLoginOperator option').evaluateAll(xs=>xs.find(x=>/michael/i.test(x.value))?.value);await page.selectOption('#optykerLoginOperator',op);await page.waitForSelector('#optykerAuthPassword',{state:'visible'});await page.fill('#optykerAuthPassword',base.password);await page.click('.optykerLoginButton');await page.waitForFunction(()=>window.optykerAuthenticated);
 await page.click('#navClients');await page.evaluate(({cid,clients})=>{OPTYKER_CLOUD.clients=clients;clientSelect(cid);},{cid,clients});await page.click('#clientSheetActionsDock [data-cs-launch=eyewear]');await page.click('[data-cs-id="'+sid+'"] [data-cs-open]');await page.click('[data-dl-open]');await page.waitForSelector('[data-dl-field=issuer_name]');
 for(const [k] of ALL_FIELDS){const e=page.locator('[data-dl-field="'+k+'"]');if(await e.evaluate(x=>x.tagName==='SELECT'))await e.selectOption(vals[k]||'');else await e.fill(vals[k]||'');}
 await page.check('[data-dl-check=technical_verified]');await page.check('[data-dl-check=conformity_confirmed]');await page.click('[data-dl-prepare]');await page.waitForSelector('[data-dl-pad=operator]');await page.click('[data-dl-sign]');assert((await page.locator('#ovcDeliveryDialog footer').textContent()).includes('entrambe'));
 for(const role of ['operator','client']){const r=await page.locator('[data-dl-pad='+role+']').boundingBox();await page.mouse.move(r.x+35,r.y+50);await page.mouse.down();for(let i=0;i<14;i++)await page.mouse.move(r.x+35+i*17,r.y+50+18*Math.sin(i),{steps:2});await page.mouse.up();}
 for(const k of ['identity_checked','instructions_delivered','client_accepts'])await page.check('[data-dl-check='+k+']');await page.screenshot({path:OUT+'/firme-su-optyker.png',fullPage:false});await page.click('[data-dl-sign]');await page.waitForSelector('[data-dl-print]');assert((await page.locator('#ovcDeliveryDialog main').textContent()).includes('Revisione 2'));await page.screenshot({path:OUT+'/archivio-firmato.png'});report.checks.push('Actual saved-busta button, full form, frozen preview, real canvas signatures and server archive roundtrip from browser');
 await page.click('[data-dl-close]');await page.click('[data-dl-open]');await page.waitForSelector('[data-dl-archive]');assert.equal(await page.locator('[data-dl-archive]').count(),2);await page.locator('[data-dl-archive]').last().click();await page.waitForSelector('[data-dl-print]');assert((await page.locator('#ovcDeliveryDialog main').textContent()).includes('Revisione 1'));report.checks.push('Reopen original signed revision without overwriting it; exact archived PDF remains printable');
 await page.evaluate(()=>{window.clientCurrentId='22222222-2222-4222-8222-222222222222';});await page.waitForTimeout(650);assert.equal(await page.locator('#ovcDeliveryDialog').count(),0);report.checks.push('Customer/session change closes sensitive document view');
 report.ok=true;
}catch(e){report.error=String(e);if(page)await page.screenshot({path:OUT+'/failure.png'}).catch(()=>{});throw e;}
finally{fs.writeFileSync(OUT+'/result.json',JSON.stringify(report,null,2));console.log(report);await browser?.close();await pg.end();}
