/* Isolated browser tests. All business APIs are mocked; no customer data or fiscal writes. */
const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),vm=require('node:vm'),http=require('http');
const root=process.cwd(),out=path.join(root,'sept11-check');fs.mkdirSync(out,{recursive:true});
const source=n=>fs.readFileSync(path.join(root,n),'utf8');
const harness=`<!doctype html><html><head><style>body{font-family:Arial;margin:24px}.panel{padding:15px}input,button,select{padding:9px}#clientAnagraficaSection{padding:20px}</style></head><body><nav id="moduleNav"><button id="navDashboard" class="moduleBtn active">Dashboard</button><button id="navClients">Clienti</button><button id="navWarehouse">Magazzino</button><button id="navSettings">Impostazioni</button></nav><div id="dashboardPanel" class="panel">Dashboard</div><div id="clientsPanel" class="panel" style="display:none"><div><h2 id="clientWorkspaceName">Cliente A</h2></div><section id="clientAnagraficaSection"><input id="unsavedInput" value="NON CANCELLARE"></section></div><div id="warehousePanel" class="panel" style="display:none"><div class="whHeadActions"></div><select id="whCategory"><option value="services">Servizi</option><option value="frames">Montature</option></select></div><div id="optykerSettingsPanel" class="panel" style="display:none">Impostazioni</div><div id="decoy" class="panel">Testo con Impostazioni, non è la sezione</div><div id="eyewearPanel" style="display:none"><select id="eyFrameType"><option>Del cliente</option><option>Cerchiata</option></select><input id="eyFramePrice" value="900"><div id="eyWarrantyBox"><select id="eyWarranty"><option>Gold</option></select><p class="eyWarrantyHint"></p></div><button id="eyModeQuote" class="active">Preventivo</button><div id="eyRecentList"><div class="eyRecentRow">Preventivo 1P26</div></div></div></body></html>`;
const server=http.createServer((req,res)=>{try{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/harness'){res.setHeader('Content-Type','text/html');return res.end(harness)}const f=path.resolve(root,'_site','.'+p);if(!f.startsWith(path.join(root,'_site')+path.sep))throw Error('bad path');const file=fs.statSync(f).isDirectory()?path.join(f,'index.html'):f;res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch(e){res.statusCode=404;res.end('not found')}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});let checks=[];try{
 const assembled=source('_site/index.html');assert(!assembled.includes('id="optykerSingleRootViewJs"'));assert(assembled.includes('id="optykerSept11Js"'));assert(assembled.includes('optykerQuotePrint.decorate'));
 for(const alias of ['gestionale-v2','gestionale-v3'])assert.equal(source('_site/'+alias+'/index.html'),assembled);
 let count=0;for(const m of assembled.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/\bsrc\s*=/.test(m[1])||/type=["'](?:application|importmap)/.test(m[1])||!m[2].trim())continue;new vm.Script(m[2],{filename:'built-inline-'+(++count)});}checks.push('All '+count+' assembled inline scripts parse; desktop aliases identical');
 const ctx=await browser.newContext({viewport:{width:1240,height:850}});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await ctx.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.fulfill({status:503,body:'External requests blocked in UI test'}));
 await page.goto(base+'/harness');await page.addStyleTag({content:source('optyker-sept11.css')});
 await page.evaluate(()=>{window.optykerAuthenticated=true;window.OPTYKER_CLOUD={username:'TEST_OPERATOR',password:'NOT_A_REAL_PASSWORD',root:location.origin,key:'MOCK',sheets:{}};window.clientCurrentId='11111111-1111-4111-8111-111111111111';window.showModule=function(){document.getElementById('clientsPanel').style.display='block'};window.showDashboard=function(){document.getElementById('dashboardPanel').style.display='block'};window.openWarehouse=function(){document.getElementById('warehousePanel').style.display='block'};window.optykerOpenSettings=function(){document.getElementById('optykerSettingsPanel').style.display='block'};window.openEyewearSheet=function(){};window.__calls=[];window.__quotes=[];window.fetch=async(url,opts)=>{let b=JSON.parse(opts.body);window.__calls.push({url,b});if(String(url).includes('quotes-api'))return new Promise(resolve=>window.__quotes.push({client:b.client_id,resolve}));if(String(url).endsWith('optyker_ovc_client_prices_api'))return Response.json({ok:true,data:b.p_action==='set'?{revision:2}:[{id:'44444444-4444-4444-8444-444444444444',title:'Controllo',standard_price:75,default_card_price:40,card_price:null,revision:0}]});if(String(url).endsWith('optyker_ovc_api'))return Response.json({ok:true,data:[{id:'44444444-4444-4444-8444-444444444444',title:'Controllo',standard_price:75,card_price:40,revision:1}]});if(String(url).endsWith('optyker_eyewear_warranty_api'))return Response.json({ok:true,data:[]});if(String(url).endsWith('optyker_client_billing_api'))return Response.json({ok:true,provider:{connected:true},client:{id:b.p_payload.client_id,name:'Cliente A',tax_code:'TEST',address_city:'Lallio'},data:[],drafts:[],pos_requests:[{id:'55555555-5555-4555-8555-555555555555',total:100,issue_date:'2026-09-11',header:'Saldo già pagato'}]});if(b.action==='login')return Response.json({ok:true,token:'MOCK_ADMIN_ONLY'});return Response.json({ok:true,data:[]});};});
 await page.addScriptTag({content:source('optyker-sept11.js')});await page.addScriptTag({content:source('eyewear-ui-fix-v11.js')});
 await page.evaluate(()=>showModule('clients'));assert(await page.locator('#clientsPanel').isVisible());await page.evaluate(()=>openWarehouse());assert(await page.locator('#warehousePanel').isVisible());assert(!(await page.locator('#clientsPanel').isVisible()));await page.evaluate(()=>document.getElementById('clientsPanel').style.setProperty('display','block','important'));await page.waitForTimeout(80);assert(!(await page.locator('#clientsPanel').isVisible()));await page.evaluate(()=>showModule('clients'));assert.equal(await page.inputValue('#unsavedInput'),'NON CANCELLARE');checks.push('Switching root hides previous view including late inline !important callbacks, preserves fields');
 await page.evaluate(()=>openEyewearSheet());await page.waitForTimeout(100);assert.deepEqual(await page.locator('#eyWarranty option').allTextContents(),['Base · inclusa']);assert((await page.locator('.eyWarrantyHint').textContent()).includes('massimo due ricambi complessivi'));await page.selectOption('#eyFrameType','Cerchiata');await page.waitForTimeout(80);assert.deepEqual(await page.locator('#eyWarranty option').allTextContents(),['Base · inclusa','Gold · + € 100']);await page.fill('#eyFramePrice','100');await page.waitForTimeout(80);assert.deepEqual(await page.locator('#eyWarranty option').allTextContents(),['Base · inclusa','Silver · + € 20']);checks.push('Client frame permits Base only; provided frame retains Silver/Gold eligibility');
 const warehouse=source('warehouse.js');assert(!warehouse.includes('id="whCompaniesBtn"'));const a=warehouse.indexOf('function installSettingsCompanyCard(){'),b=warehouse.indexOf('function outsideClick',a);await page.addScriptTag({content:'function E(id){return document.getElementById(id)} function openCompanies(){} '+warehouse.slice(a,b)+';installSettingsCompanyCard();'});assert.equal(await page.locator('#optykerSettingsPanel > #whSettingsCompanies').count(),1);assert.equal(await page.locator('#decoy #whSettingsCompanies').count(),0);checks.push('Supplier management exists only under actual Settings, never broad text matches');
 await page.evaluate(()=>showModule('clients'));await page.addScriptTag({content:source('quotes.js')});await page.waitForFunction(()=>window.__quotes.length===1);await page.evaluate(()=>{window.clientCurrentId='22222222-2222-4222-8222-222222222222';document.getElementById('clientWorkspaceName').textContent='Cliente B';window.refreshClientQuotes()});await page.waitForFunction(()=>window.__quotes.length===2);await page.evaluate(()=>{const q=__quotes[1];q.resolve(Response.json({ok:true,data:[{id:'QB',client_id:q.client,sheet_type:'eyewear_quote',title:'Preventivo B',reference_code:'SOLO-B',data:{pricing:{total:100}}}]}));});await page.waitForFunction(()=>document.getElementById('optykerClientQuotesSection').textContent.includes('SOLO-B'));await page.evaluate(()=>__quotes[0].resolve(Response.json({ok:true,data:[{id:'QA',sheet_type:'eyewear_quote',reference_code:'ERRATO-A',data:{}}]})));await page.waitForTimeout(80);assert(!(await page.locator('#optykerClientQuotesSection').textContent()).includes('ERRATO-A'));assert.equal(await page.locator('.optykerQuoteTitle').evaluate(e=>getComputedStyle(e).color),'rgb(180, 35, 50)');checks.push('Late quote response cannot show previous customer; quotes red');
 await page.waitForTimeout(850);await page.evaluate(()=>optykerOpenOvcClientTariffs(window.clientCurrentId,'Cliente B'));await page.waitForSelector('.ovc11TariffRow');await page.fill('.ovc11TariffRow input','0');await page.click('.ovc11TariffRow button');await page.waitForFunction(()=>document.querySelector('.ovc11TariffRow [role=status]').textContent==='Prezzo personalizzato salvato');const saved=await page.evaluate(()=>__calls.findLast(c=>c.b.p_action==='set'));assert.equal(saved.b.p_payload.client_id,'22222222-2222-4222-8222-222222222222');assert.equal(saved.b.p_payload.card_price,0);assert(saved.url.endsWith('optyker_ovc_client_prices_api'));await page.click('dialog[open] header button');await page.evaluate(()=>OPTYKER_SEPT11.openTariffs());await page.waitForSelector('.ovc11TariffRow');assert.equal(await page.inputValue('.ovc11TariffRow input'),'40,00');await page.click('dialog[open] header button');checks.push('Personal zero price saves to captured customer only; global tariff unchanged');
 await page.evaluate(()=>optykerOpenClientBilling(window.clientCurrentId));await page.waitForSelector('[data-pos]');await page.click('[data-pos]');await page.waitForSelector('dialog[open] input[type=password]');await page.evaluate(()=>window.OptykerInvoices={open:o=>window.__invoiceOptions=o});await page.fill('dialog[open] input[type=password]','MOCK_NOT_REAL');await page.click('dialog[open] button[type=submit]');await page.waitForFunction(()=>!!window.__invoiceOptions);const invoice=await page.evaluate(()=>({prefill:__invoiceOptions.prefill,user:OPTYKER_CLOUD.username,calls:__calls.map(c=>c.b.action).filter(Boolean)}));assert.equal(invoice.prefill.client_id,'22222222-2222-4222-8222-222222222222');assert.equal(invoice.prefill.pos_source_id,'55555555-5555-4555-8555-555555555555');assert.equal(invoice.prefill.channel,'');assert.equal(invoice.prefill.items.length,0);assert.match(invoice.prefill.date,/^2026-\d\d-\d\d$/);assert.equal(invoice.user,'TEST_OPERATOR');assert(!invoice.calls.includes('fic_create')&&!invoice.calls.includes('fic_send'));checks.push('Pending POS request links to correct FIC customer/draft, admin authorizes separately, no guessed VAT or emission');

 // Customer-context composer must never offer navigation to another customer's drafts.
 await page.addScriptTag({content:source('billing-compose.js')});
 await page.evaluate(()=>OptykerInvoices.open({clientId:clientCurrentId,prefill:__invoiceOptions.prefill,call:async()=>({series:[{code:'retail',year:2026,label:'Dettaglio',last_number:0,suffix:'/D'}],info:{vat_types_list:[{id:1,value:22,description:'Test'}],countries_list:['Italia']}})}));
 await page.waitForSelector('#ficForm');assert(!(await page.locator('#ficNew').isVisible()));assert(!(await page.locator('#ficList').isVisible()));assert.equal(await page.inputValue('#fic_name'),'Cliente A');assert.equal(await page.locator('[data-k=vat_id]').inputValue(),'');assert((await page.locator('#ficBody').textContent()).includes('non incassare nuovamente'));await page.click('#ficClose');checks.push('Real customer composer preserves context, hides global navigation, requires VAT and warns against double collection');
 // Real prescription header template from assembled source, same dimensions and clinic text.
 const hm=assembled.match(/<div class="head"><img src="[^]*?<\/div><\/div>/);assert(hm,'Prescription header template missing');const svg='data:image/svg+xml;base64,'+Buffer.from(source('visualcare-logo.svg')).toString('base64');const header=hm[0].replace(/src="[^"]*"/, 'src="'+svg+'"');const rules=assembled.match(/\.head\{[^}]+\}\.head img\{[^}]+\}\.clinic\{[^}]+\}\.clinic b\{[^}]+\}/);assert(rules,'Prescription header styles missing');
 const printHtml=await page.evaluate(({header,rules})=>{window.prescriptionPrintHtml=()=>'<html><head><style>'+rules+'</style></head><body>'+header+'</body></html>';const html=optykerQuotePrint.decorate('<html><body><h1>Old title</h1><p>Preventivo test · montatura del cliente</p><p>'+OPTYKER_SEPT11.ownText+'</p></body></html>','Preventivo occhiali','TEST-P26 · Cliente di prova');const d=new DOMParser().parseFromString(html,'text/html');d.querySelector('.head').removeAttribute('data-ovc-print-header');if(d.querySelector('.head').outerHTML!==new DOMParser().parseFromString(prescriptionPrintHtml(),'text/html').querySelector('.head').outerHTML)throw Error('Different prescription header');return html;},{header,rules:rules[0]});
 const print=await ctx.newPage();await print.setContent(printHtml);await print.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));assert.equal(await print.locator('.head').count(),1);const image=await print.locator('.head img').boundingBox();assert.equal(image.width,150);assert.equal(image.height,150);await print.pdf({path:path.join(out,'preventivo-test.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});await print.screenshot({path:path.join(out,'preventivo-test.png'),fullPage:true});checks.push('Printed quote reuses exact prescription header/150px logo and commercial warranty text');
 await page.evaluate(()=>showModule('clients'));await page.screenshot({path:path.join(out,'cliente-test.png'),fullPage:true});assert.deepEqual(errors,[]);checks.push('No browser JavaScript exceptions in tested workflows');
 await ctx.close();fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({ok:true,checks},null,2));console.log(JSON.stringify({ok:true,checks},null,2));
 }catch(e){fs.writeFileSync(path.join(out,'failure.txt'),e.stack);throw e;}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
