import test from 'node:test';import assert from 'node:assert/strict';
import {ovcContext,serviceProduct,serviceForId} from '../supabase/functions/optyker-cash-register-api/ovc.mjs';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333',I='44444444-4444-4444-8444-444444444444';
function setup(){
 const data={optyker_inventory_items:[{id:I,price:75,title:'Controllo',category:'services',active:true,shopify_variant_id:'1234',vat_code:'22'}],optyker_ovc_cards:[{client_id:A,card_number:1,active:true,revision:1},{client_id:B,card_number:2,active:true,revision:1},{client_id:C,card_number:3,active:true,revision:1}],optyker_ovc_service_prices:[{item_id:I,card_price:40,revision:2}],optyker_ovc_client_service_prices:[{client_id:A,item_id:I,card_price:30,revision:3},{client_id:B,item_id:I,card_price:0,revision:4},{client_id:C,item_id:I,card_price:null,revision:5}]};
 const db={from(table){let filters=[];const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},order(){return q},limit(){return Promise.resolve({data:structuredClone(data[table].filter(r=>filters.every(f=>f(r)))),error:null})},maybeSingle(){return Promise.resolve({data:structuredClone(data[table].find(r=>filters.every(f=>f(r)))),error:null})}};return q;}};return {db,data};
}
async function price(db,cid){const ctx=await ovcContext(db,cid);return serviceForId('service:'+I,ctx);}
test('Customer prices override warehouse defaults without cross-customer leakage',async()=>{const {db}=setup();assert.equal((await price(db,A)).price,30);assert.equal((await price(db,B)).price,0);assert.equal((await price(db,C)).price,40);assert.equal((await price(db,A)).price,30);});
test('Changing the default affects only inherited prices',async()=>{const {db,data}=setup();data.optyker_ovc_service_prices[0].card_price=50;assert.equal((await price(db,A)).price,30);assert.equal((await price(db,B)).price,0);assert.equal((await price(db,C)).price,50);});
test('Clearing an override restores inheritance; clearing both uses warehouse price',async()=>{const {db,data}=setup();data.optyker_ovc_client_service_prices[0].card_price=null;assert.equal((await price(db,A)).price,40);data.optyker_ovc_service_prices[0].card_price=null;assert.equal((await price(db,A)).price,75);});
test('Inactive or absent cards use standard prices, including personal free tariffs',async()=>{const {db,data}=setup();data.optyker_ovc_cards[1].active=false;assert.equal((await price(db,B)).price,75);assert.equal((await price(db,'')).price,75);});
test('Shopify service identifiers cannot bypass personal prices',async()=>{const {db}=setup();const ctx=await ovcContext(db,A);assert.equal(serviceForId('gid://shopify/ProductVariant/1234',ctx).price,30);assert.equal(serviceForId('service:'+I,ctx).ovc_price_source,'client');assert.equal(serviceForId('service:'+I,ctx).ovc_client_revision,3);});
test('Price reads fail closed when customer overrides cannot be fetched',async()=>{const {db}=setup();const original=db.from;db.from=t=>t==='optyker_ovc_client_service_prices'?{select(){return this},eq(){return this},limit(){return Promise.resolve({error:Error('DB unavailable')})}}:original(t);await assert.rejects(ovcContext(db,A),/unavailable/);});
