/* Shopify account view. All entitlements and counters come from the same Optyker server as the app. */
(function(){
'use strict';const VERSION='20260912-cover-channels1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'da confermare';
const states={pending:'In attesa dell’ottica',fulfilled:'Ricambio consegnato',rejected:'Non accolta / annullata'};
let active=null;
function unmount(){if(active){active.urls.forEach(u=>URL.revokeObjectURL(u));active.cancelled=true;active=null;}}
function valid(v){return active===v&&!v.cancelled&&v.root.isConnected&&v.options.valid();}
function note(v,text){if(valid(v))v.root.querySelector('[data-sw-note]').textContent=text;}
function view(v,html){if(!valid(v))return;v.root.innerHTML='<section class="swCover">'+html+'<p data-sw-note role="status" aria-live="polite"></p></section>';}
async function call(v,action,p={}){if(!valid(v))throw Error('Schermata cambiata: riapri la garanzia.');const x=await v.options.request(action,p);if(!valid(v))throw Error('Schermata cambiata: riapri la garanzia.');if(x.ok!==true)throw Error(x.error||'Garanzia non disponibile');return x;}
const chat=v=>{if(valid(v)){const fn=v.options.chat;unmount();fn();}};
function buttons(v){v.root.querySelector('[data-sw-chat]')?.addEventListener('click',()=>chat(v));v.root.querySelector('[data-sw-list]')?.addEventListener('click',()=>list(v));}
async function list(v){view(v,'<h2>Occhiali e garanzie</h2><p>Caricamento…</p>');try{const x=await call(v,'list');v.rows=x.data;view(v,'<h2>Occhiali e garanzie</h2><p>Coperture, richieste e ricambi condivisi con l’app e il centro ottico.</p>'+(x.data.length?x.data.map(r=>'<article class="swCard"><h3>'+esc([r.frame?.brand,r.frame?.model].filter(Boolean).join(' · ')||r.frame?.type||'Occhiale')+'</h3><p>'+esc(r.reference)+' · '+date(r.created_at)+'</p><p><b>Garanzia '+esc(r.warranty_name)+'</b></p><p>Lente OD: '+esc(r.lenses?.od||'Non specificata')+'<br>Lente OS: '+esc(r.lenses?.os||'Non specificata')+'</p><div class="swButtons"><button type="button" data-sw-open="'+esc(r.id)+'">Apri garanzia</button><button type="button" data-sw-cert="'+esc(r.id)+'">Vedi certificato firmato</button></div></article>').join(''):'<p>Non risultano Buste Occhiali associate alla tua anagrafica.</p>')+'<button type="button" data-sw-refresh>Aggiorna</button><button type="button" data-sw-chat>Apri chat assistenza</button>');
 v.root.querySelectorAll('[data-sw-open]').forEach(b=>b.onclick=()=>open(v,b.dataset.swOpen));v.root.querySelectorAll('[data-sw-cert]').forEach(b=>b.onclick=()=>certificate(v,b.dataset.swCert));v.root.querySelector('[data-sw-refresh]').onclick=()=>list(v);buttons(v);note(v,'Garanzia commerciale OVC · '+VERSION);
 }catch(e){view(v,'<h2>Occhiali e garanzie</h2><button type="button" data-sw-refresh>Riprova</button><button type="button" data-sw-chat>Apri chat assistenza</button>');if(valid(v)){v.root.querySelector('[data-sw-refresh]').onclick=()=>list(v);buttons(v);note(v,e.message);}}}
async function open(v,sid){v.sid=sid;view(v,'<button type="button" data-sw-list>‹ Tutti gli occhiali</button><p>Caricamento garanzia…</p>');buttons(v);try{v.x=await call(v,'get',{sheet_id:sid});coverage(v);}catch(e){note(v,e.message);}}
function coverage(v){const c=v.x.coverage;view(v,'<button type="button" data-sw-list>‹ Tutti gli occhiali</button><h2>Garanzia '+esc(c.name)+'</h2><p>'+esc(v.x.reference)+'</p>'+ (c.starts_on?'<p>Consegna: <b>'+date(c.starts_on)+'</b> · termine: giorno precedente il '+date(c.ends_before)+'</p>':'<p class="swNotice"><b>Data di consegna da confermare in ottica.</b> Non viene usata automaticamente la data di creazione della busta.</p>')+(c.state==='expired'?'<p class="swNotice">Copertura di 24 mesi terminata.</p>':'')+(['base','base_solo_lenti'].includes(c.tier)?'<p class="swQuota">Lenti: '+c.replacements_used+' ricambi utilizzati · '+c.replacements_pending+' richieste in attesa · '+c.replacements_remaining+' disponibili su 2 in due anni.</p>':'')+
 c.benefits.map((b,i)=>'<article class="swCard"><h3>'+esc(b.label)+'</h3><p>'+esc(b.terms)+'</p><button type="button" data-sw-reason="'+i+'">'+(b.reason==='loss'?'Denuncia e richiesta in chat':b.eligible?(b.discount_percent===100?'Richiedi ricambio in omaggio':'Richiedi con sconto '+b.discount_percent+'%'):'Vedi condizioni / assistenza')+'</button></article>').join('')+'<h3>Richieste per questo occhiale</h3>'+(v.x.claims.length?v.x.claims.map(r=>'<p><b>'+esc(c.benefits.find(b=>b.reason===r.reason)?.label||r.reason)+(r.eye?' · '+esc(r.eye):'')+'</b><br>'+esc(states[r.status]||r.status)+' · '+date(r.created_at)+'</p>').join(''):'<p>Nessuna richiesta.</p>')+'<p class="swNotice">La richiesta viene verificata dall’ottica. Nessun addebito o ordine automatico.</p><button type="button" data-sw-chat>Apri chat assistenza</button>');buttons(v);v.root.querySelectorAll('[data-sw-reason]').forEach(b=>b.onclick=()=>form(v,c.benefits[Number(b.dataset.swReason)]));}
function form(v,b){v.benefit=b;v.requestId=crypto.randomUUID();const allowed=b.eligible&&(b.reason!=='scratched_lens'||v.x.coverage.replacements_remaining>0);
 view(v,'<button type="button" data-sw-back>‹ Torna alla garanzia</button><h2>'+esc(b.label)+'</h2><p>'+esc(b.terms)+'</p>'+(!allowed?'<p class="swNotice">Richiesta non disponibile: controlla la data di consegna, il periodo di copertura e i ricambi residui.</p>':'')+(b.reason==='scratched_lens'?'<label>Lente interessata<select data-sw-eye><option value="">Seleziona</option><option value="OD">Destra (OD)</option><option value="OS">Sinistra (OS)</option><option value="entrambi">Entrambe</option></select></label>':'')+
 (b.reason==='loss'?'<p>Inoltra la denuncia nella chat privata con l’ottica. Il documento sarà verificato prima della sostituzione.</p><label>Denuncia, massimo 3 MB<input type="file" data-sw-file accept="application/pdf,image/jpeg,image/png,image/webp"></label><button type="button" data-sw-upload>Invia denuncia in chat</button><label>Denuncia già inviata per questa busta<select data-sw-report><option value="">Seleziona</option>'+v.x.reports.map(r=>'<option value="'+esc(r.id)+'">'+esc(r.name)+' · '+date(r.created_at)+'</option>').join('')+'</select></label>':'')+'<button type="button" data-sw-send '+(!allowed?'disabled':'')+'>Conferma e invia richiesta all’ottica</button><button type="button" data-sw-chat>Apri chat assistenza</button><p>Nessun pagamento da questo pulsante.</p>');buttons(v);v.root.querySelector('[data-sw-back]').onclick=()=>coverage(v);
 const busy=on=>{v.busy=on;if(valid(v)){v.root.querySelectorAll('button').forEach(x=>x.disabled=on);const s=v.root.querySelector('[data-sw-send]');if(s)s.disabled=on||!allowed;}};
 v.root.querySelector('[data-sw-send]').onclick=async()=>{if(v.busy||!allowed)return;const eye=v.root.querySelector('[data-sw-eye]')?.value||'',evidence=v.root.querySelector('[data-sw-report]')?.value||null;if(b.reason==='scratched_lens'&&!eye){note(v,'Seleziona la lente.');return;}if(b.reason==='loss'&&!evidence){note(v,'Inoltra prima la denuncia e selezionala.');return;}if(!confirm('Inviare la richiesta per '+b.label+'?\n'+b.terms+'\nNessun addebito automatico.'))return;busy(true);try{const x=await call(v,'request',{sheet_id:v.sid,request_id:v.requestId,reason:b.reason,eye,evidence_message_id:evidence,confirm:true});await open(v,v.sid);note(v,x.already_requested?'Richiesta già ricevuta: nessun duplicato.':'Richiesta ricevuta e visibile in chat.');}catch(e){note(v,e.message);}finally{busy(false);}};
 v.root.querySelector('[data-sw-upload]')?.addEventListener('click',async()=>{if(v.busy)return;const f=v.root.querySelector('[data-sw-file]').files?.[0];if(!f||f.size>3*1024*1024){note(v,'Seleziona un PDF o una foto fino a 3 MB.');return;}if(!confirm('Inviare questo documento nella chat privata con Ottica Visual Care?'))return;busy(true);try{const data=await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=()=>rej(Error('File non leggibile'));fr.readAsDataURL(f);});if(v.uploadData!==data){v.uploadId=crypto.randomUUID();v.uploadData=data;}const x=await call(v,'report',{sheet_id:v.sid,request_id:v.uploadId,confirm:true,attachment_data:data,attachment_name:f.name,attachment_type:f.type});v.x=await call(v,'get',{sheet_id:v.sid});form(v,b);v.root.querySelector('[data-sw-report]').value=x.evidence_message_id;note(v,'Denuncia inviata in chat. Conferma ora la richiesta.');}catch(e){note(v,e.message);}finally{busy(false);}});
}
async function certificate(v,sid){view(v,'<button type="button" data-sw-list>‹ Tutti gli occhiali</button><h2>Certificato firmato</h2><p data-sw-doc>Caricamento…</p><button type="button" data-sw-chat>Apri chat assistenza</button>');buttons(v);try{const x=await call(v,'certificate',{sheet_id:sid});if(!x.data){v.root.querySelector('[data-sw-doc]').textContent=x.message;return;}const d=x.data,bytes=Uint8Array.from(atob(d.pdf_base64.replace(/\s/g,'')),c=>c.charCodeAt(0));const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==d.pdf_sha256)throw Error('Verifica del documento non riuscita');if(!valid(v))return;const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));v.urls.push(url);v.root.querySelector('[data-sw-doc]').innerHTML='Copia archiviata · '+esc(d.reference)+'<br>Consegna: '+date(d.delivery_date)+'<br><a href="'+url+'" target="_blank" rel="noopener">Apri il PDF firmato</a>';}catch(e){note(v,e.message);}}
function mount(root,options){unmount();const v={root,options,urls:[],cancelled:false,busy:false};active=v;list(v);}
window.OPTYKER_SHOP_COVER={version:VERSION,mount,unmount};
})();
