import 'react-native-url-polyfill/auto';
import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Modal,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {registerRootComponent} from 'expo';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {createClient} from '@supabase/supabase-js';
import {WebView} from 'react-native-webview';
import App from './App';

const U='https://whgziwaegjzqsgcntesr.supabase.co';
const K='sb_publishable_DndhLvY32YeCmqWMNRi30g_dEDm8upv';
const API=U+'/functions/v1/optyker-mobile-appointments';
const BOOK=U+'/functions/v1/optyker-appointments-booking?source=mobile';
const sb=createClient(U,K,{auth:{storage:AsyncStorage,autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});

async function call(action,payload={}){const {data}=await sb.auth.getSession();const token=data?.session?.access_token;if(!token)throw Error('Accedi prima di aprire gli appuntamenti.');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,apikey:K},body:JSON.stringify({action,payload})});const x=await r.json().catch(()=>({ok:false,error:'Risposta non valida'}));if(!r.ok||x?.ok===false)throw Error(x?.error||'Errore appuntamenti');return x}
const fmt=v=>new Intl.DateTimeFormat('it-IT',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
function StaffAgenda({onBook}){const [rows,setRows]=useState([]),[busy,setBusy]=useState(true),[err,setErr]=useState('');async function load(){try{setBusy(true);setErr('');const d=new Date();d.setDate(d.getDate()-1);const to=new Date();to.setDate(to.getDate()+31);const x=await call('list',{from:d.toISOString(),to:to.toISOString()});setRows(Array.isArray(x.data)?x.data:[])}catch(e){setErr(e.message)}finally{setBusy(false)}}useEffect(()=>{load()},[]);if(busy)return <View style={s.center}><ActivityIndicator/><Text style={s.muted}>Carico agenda…</Text></View>;return <ScrollView contentContainerStyle={s.pad}><View style={s.topRow}><View><Text style={s.kicker}>OTTICA VISUAL CARE</Text><Text style={s.title}>Agenda</Text></View><Pressable style={s.primary} onPress={onBook}><Text style={s.primaryText}>+ Nuovo</Text></Pressable></View>{!!err&&<Text style={s.err}>{err}</Text>}{!rows.length?<View style={s.empty}><Text style={s.emptyTitle}>Nessun appuntamento</Text><Text style={s.muted}>Gli appuntamenti confermati compariranno qui.</Text></View>:rows.map(a=><View key={a.id} style={[s.appt,{borderLeftColor:a.service_color||'#1769aa'}]}><View style={s.between}><Text style={s.time}>{fmt(a.starts_at)}</Text><Text style={s.status}>{a.status}</Text></View><Text style={s.client}>{`${a.last_name||''} ${a.first_name||''}`.trim()}</Text><Text style={s.meta}>{a.service_name} · {a.operator_username} · {a.studio_name}</Text><Text style={s.meta}>{a.phone||''} {a.email?`· ${a.email}`:''}</Text></View>)}<Pressable style={s.secondary} onPress={load}><Text style={s.secondaryText}>Aggiorna agenda</Text></Pressable></ScrollView>}
function Hub({visible,onClose}){const [mode,setMode]=useState('checking'),[url,setUrl]=useState(BOOK);useEffect(()=>{if(!visible)return;setMode('checking');call('list',{from:new Date(Date.now()-86400000).toISOString(),to:new Date(Date.now()+86400000).toISOString()}).then(()=>setMode('staff')).catch(()=>call('booking').then(x=>{setUrl(x.url||BOOK);setMode('booking')}).catch(()=>{setUrl(BOOK);setMode('booking')}))},[visible]);return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={s.modal}><View style={s.modalHead}><Pressable onPress={onClose}><Text style={s.close}>‹ Chiudi</Text></Pressable><Text style={s.modalTitle}>Appuntamenti</Text><View style={{width:55}}/></View>{mode==='checking'?<View style={s.center}><ActivityIndicator/><Text style={s.muted}>Apro gli appuntamenti…</Text></View>:mode==='staff'?<StaffAgenda onBook={()=>setMode('booking')}/>:<WebView source={{uri:url}} startInLoadingState renderLoading={()=><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Caricamento prenotazioni…</Text></View>} />}</SafeAreaView></Modal>}
function Root(){const [open,setOpen]=useState(false);return <View style={{flex:1}}><App/><Pressable accessibilityLabel="Appuntamenti" style={s.fab} onPress={()=>setOpen(true)}><Text style={s.fabIcon}>▦</Text><Text style={s.fabText}>Agenda</Text></Pressable><Hub visible={open} onClose={()=>setOpen(false)}/></View>}
const s=StyleSheet.create({fab:{position:'absolute',right:14,bottom:Platform.OS==='ios'?82:72,backgroundColor:'#173e69',borderRadius:25,minHeight:48,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:6,shadowColor:'#000',shadowOpacity:.18,shadowRadius:8,elevation:7},fabIcon:{color:'#fff',fontSize:19,fontWeight:'900'},fabText:{color:'#fff',fontSize:11,fontWeight:'900'},modal:{flex:1,backgroundColor:'#f4f7fa'},modalHead:{height:54,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:'#dce6ee',paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{color:'#1769aa',fontWeight:'900'},modalTitle:{color:'#17324a',fontSize:16,fontWeight:'900'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:10},muted:{color:'#6d8291',fontSize:12},pad:{padding:14,paddingBottom:30,gap:9},topRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:5},kicker:{fontSize:9,letterSpacing:1.1,fontWeight:'900',color:'#1769aa'},title:{fontSize:28,fontWeight:'900',color:'#17324a'},primary:{backgroundColor:'#1769aa',paddingHorizontal:15,paddingVertical:11,borderRadius:11},primaryText:{color:'#fff',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#b9ccda',padding:12,borderRadius:11,alignItems:'center',marginTop:5},secondaryText:{color:'#17324a',fontWeight:'900'},appt:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6ee',borderLeftWidth:6,borderRadius:13,padding:12},between:{flexDirection:'row',justifyContent:'space-between',gap:10},time:{fontWeight:'900',color:'#17324a',fontSize:12},status:{fontSize:9,fontWeight:'900',color:'#6d8291',textTransform:'uppercase'},client:{fontSize:15,fontWeight:'900',color:'#17324a',marginTop:4},meta:{fontSize:10,color:'#6d8291',marginTop:2},empty:{backgroundColor:'#fff',borderWidth:1,borderColor:'#dce6ee',borderRadius:13,padding:22,alignItems:'center'},emptyTitle:{fontWeight:'900',color:'#17324a',marginBottom:5},err:{color:'#b42318',fontSize:11,fontWeight:'700'}});
registerRootComponent(Root);
