import { createClient } from "jsr:@supabase/supabase-js@2";
export const U=Deno.env.get("SUPABASE_URL")||"";
const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const SHOP=(Deno.env.get("SHOPIFY_STORE_DOMAIN")||"vkk3n8-d0.myshopify.com").trim().replace(/^https?:\/\//,"").replace(/\/$/,"");
const CID=(Deno.env.get("SHOPIFY_CLIENT_ID")||"").trim(),CSECRET=(Deno.env.get("SHOPIFY_CLIENT_SECRET")||"").trim(),VER="2026-07";
const OLD=U+"/functions/v1/optyker-cash-register-api";
export const RELEASE="20260914-pos5";
export const db=createClient(U,KEY,{auth:{autoRefreshToken:false,persistSession:false}});
let shopToken="",shopUntil=0;
export const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, authorization","Access-Control-Allow-Methods":"POST,OPTIONS","Cache-Control":"no-store"};
export const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,"Content-Type":"application/json; charset=utf-8"}});
export const norm=(v:any)=>String(v??"").trim();
export const money=(v:any)=>{const n=Number(v||0);return Number.isFinite(n)?Math.round(n*100)/100:0};
export const cents=(v:any)=>Math.round(money(v)*100);
export function gid(kind:string,v:any){const s=norm(v);if(!s)return "";if(s.startsWith("gid://"))return s;const m=s.match(/(\d+)$/);return m?`gid://shopify/${kind}/${m[1]}`:s}
export function cleanLottery(v:any){const s=norm(v).toUpperCase().replace(/\s+/g,"");if(!s)return "";if(!/^[A-Z0-9]{8}$/.test(s))throw new Error("Il codice lotteria deve avere 8 caratteri alfanumerici.");return s}
export function fiscalCode(value:any){const s=String(value||'').trim().toUpperCase();if(!/^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$/.test(s))throw new Error('Codice fiscale non valido');const odd=[1,0,5,7,9,13,15,17,19,21,2,4,18,20,11,3,6,8,12,14,16,10,22,25,24,23];let sum=0;for(let i=0;i<15;i++){const v=/\d/.test(s[i])?Number(s[i]):s.charCodeAt(i)-65;sum+=i%2?v:odd[v]}if(String.fromCharCode(65+sum%26)!==s[15])throw new Error('Carattere di controllo del codice fiscale non valido');return s}
export async function auth(body:any){const username=norm(body?.username),password=String(body?.password||"");if(!username||password.length<8)throw new Error("AUTH_REQUIRED");const {data,error}=await db.rpc("optyker_staff_login_internal",{p_username:username,p_password:password});if(error||!data?.ok)throw new Error("AUTH_REQUIRED");return String(data.username||username)}
export async function proxy(body:any){const r=await fetch(OLD,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)});const x=await r.json().catch(()=>({ok:false,error:"Risposta cassa non valida"}));if(!r.ok||x?.ok===false)throw new Error(x?.error||(`Cassa HTTP ${r.status}`));return x}
async function getToken(force=false){if(!force&&shopToken&&Date.now()<shopUntil-300000)return shopToken;if(!CID||!CSECRET)throw new Error("Shopify non configurato");const r=await fetch(`https://${SHOP}/admin/oauth/access_token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"client_credentials",client_id:CID,client_secret:CSECRET})});const x=await r.json().catch(()=>({}));if(!r.ok||!x?.access_token)throw new Error(x?.error_description||x?.error||"Accesso Shopify non disponibile");shopToken=String(x.access_token);shopUntil=Date.now()+Math.max(60,Number(x.expires_in||86399))*1000;return shopToken}
export async function gql(query:string,variables:any){let token=await getToken(false);let r=await fetch(`https://${SHOP}/admin/api/${VER}/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":token},body:JSON.stringify({query,variables})});if(r.status===401){token=await getToken(true);r=await fetch(`https://${SHOP}/admin/api/${VER}/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":token},body:JSON.stringify({query,variables})})}const x=await r.json().catch(()=>({}));if(!r.ok||x?.errors?.length)throw new Error(x?.errors?.[0]?.message||`Shopify ${r.status}`);return x?.data||{}}
export async function clientById(id:string){if(!id)return null;const {data,error}=await db.from("optyker_clients").select("id,name,surname,email,phone,pec,fiscal,vat,street,street_number,postal_code,city,province,shopify_customer_id,reference_no").eq("id",id).maybeSingle();if(error)throw error;return data||null}
export function stockQty(r:any){return r.inventory_quantity==null?(r.shopify_inventory_quantity==null?null:Number(r.shopify_inventory_quantity)):Number(r.inventory_quantity)}
async function inventoryMap(ids:any[]=[]){const vals=[...new Set(ids.map(v=>gid("ProductVariant",v)).filter(v=>v.startsWith("gid://shopify/ProductVariant/")))];if(!vals.length)return new Map();const rows:any[]=[];for(let i=0;i<vals.length;i+=100){const {data,error}=await db.from("optyker_inventory_items").select("id,shopify_product_id,shopify_variant_id,title,variant_title,vendor,product_type,sku,barcode,image_url,price,inventory_quantity,shopify_inventory_quantity,tracked,category,vat_code,active").eq("active",true).in("shopify_variant_id",vals.slice(i,i+100));if(error)throw error;rows.push(...(data||[]))}return new Map(rows.map(x=>[String(x.shopify_variant_id),x]))}
async function localProducts(search:any,limit=120){let q=db.from("optyker_inventory_items").select("id,shopify_product_id,shopify_variant_id,title,variant_title,vendor,product_type,sku,barcode,image_url,price,inventory_quantity,shopify_inventory_quantity,tracked,category,vat_code,active").eq("active",true).not("shopify_variant_id","is",null).limit(Math.max(20,Math.min(250,limit)));const s=norm(search).replace(/[%_,()]/g," ").slice(0,80);if(s)q=q.or(`title.ilike.%${s}%,variant_title.ilike.%${s}%,vendor.ilike.%${s}%,sku.ilike.%${s}%,barcode.ilike.%${s}%`);const {data,error}=await q;if(error)throw error;return data||[]}
function localProduct(r:any){const qty=stockQty(r);return {product_id:String(r.shopify_product_id||""),variant_id:String(r.shopify_variant_id||""),title:String(r.title||"Prodotto"),variant_title:String(r.variant_title||""),vendor:String(r.vendor||""),product_type:String(r.product_type||""),image:String(r.image_url||""),sku:String(r.sku||""),barcode:String(r.barcode||""),price:money(r.price),inventory_quantity:qty,available:true,needs_order:r.tracked===true&&Number(qty||0)<=0,tracked:r.tracked===true,inventory_item_id:r.id,vat_code:String(r.vat_code||""),fiscal_vat_code:String(r.vat_code||""),fiscal_item_type:r.category==="services"?"services":String(r.vat_code||"")?"goods":""}}
export async function productsV2(body:any){const base=await proxy(body),p=body.payload||{},locals=await localProducts(p.search,Number(p.first||70)*2),map=new Map<string,any>();for(const x of (Array.isArray(base.data)?base.data:[]))map.set(String(x.variant_id),{...x});for(const r of locals){const l=localProduct(r);if(!l.variant_id)continue;const b=map.get(l.variant_id);if(b)map.set(l.variant_id,{...b,inventory_quantity:l.inventory_quantity,needs_order:l.needs_order,tracked:l.tracked,inventory_item_id:l.inventory_item_id});else map.set(l.variant_id,l)}return {...base,data:[...map.values()].slice(0,Math.max(70,Math.min(180,Number(p.first||70)*2))),release:RELEASE}}
export async function missingStock(lines:any[]){const im=await inventoryMap(lines.map(x=>x?.variant_id)),missing:any[]=[];for(const l of lines){const id=gid("ProductVariant",l?.variant_id),row:any=im.get(id);if(!row||row.tracked!==true)continue;const want=Number(l?.quantity||0),have=Math.max(0,Number(stockQty(row)||0));if(want>have)missing.push({variant_id:id,quantity:want,available_quantity:have,missing_quantity:want-have,row})}return missing}
