import {cents,cleanLottery,clientById,db,fiscalCode,gid,gql,money,norm,proxy,RELEASE} from './base.ts';
import {createInvoiceDraft,createPayment,createTsDocument,paymentSnapshot,zeroFiscalSnapshot} from './fiscal.ts';
import {quoteClientCartLines} from './cart.ts';

function customDraftLine(x:any){return {title:String(x.title||'Prodotto').slice(0,255),sku:String(x.sku||'').slice(0,255),quantity:Number(x.quantity),requiresShipping:x.is_service!==true&&x.is_client_cart_order!==true,taxable:!/^(ART10|N[1-7](\.|$))/i.test(String(x.fiscal_vat_code||x.vat_code||'')),originalUnitPriceWithCurrency:{amount:money(x.price).toFixed(2),currencyCode:'EUR'},customAttributes:[{key:'Optyker variante origine',value:String(x.variant_id||x.catalog_id||'')},{key:'Da ordinare',value:x.needs_order?'SI':'NO'},...(x.is_client_cart_order?[{key:'Ordine laboratorio',value:String(x.source_work_order_id||x.variant_title||'SI')}]:[])]}}
function safeVariantLine(x:any){const id=String(x.variant_id||'');if(id.startsWith('gid://shopify/ProductVariant/')&&!x.needs_order&&!x.is_service&&!x.is_client_cart_order&&!x.catalog_id&&!x.ovc_card_applied&&!Number(x.discount_percent||0))return {variantId:id,quantity:Number(x.quantity)};return customDraftLine(x)}

export async function clientCartCheckout(body:any,operator:string,missing:any[]){
 const p=body.payload||{},linesIn=Array.isArray(p.lines)?p.lines:[];if(!linesIn.length)throw new Error('Il carrello è vuoto');
 const requestId=norm(p.request_id);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requestId))throw new Error('Identificativo incasso non valido');
 const clientId=norm(p.client_id);if(!clientId)throw new Error('Il carrello persistente richiede un cliente selezionato');
 const {data:prev,error:pe}=await db.from('optyker_pos_sales').select('*').eq('data->>checkout_request_id',requestId).maybeSingle();if(pe)throw pe;if(prev){const {data:ps}=await db.from('optyker_pos_payments').select('*').eq('sale_id',prev.id).order('created_at');return {...prev,payment:ps?.[0]||null,missing_items:prev.data?.missing_items||[],manual_lottery_required:!!prev.data?.lottery_code,recovered:true}}

 const cartInput=linesIn.filter((l:any)=>String(l?.variant_id||'').startsWith('client_cart:'));
 const ordinaryInput=linesIn.filter((l:any)=>!String(l?.variant_id||'').startsWith('client_cart:'));
 const missMap=new Map(missing.map(m=>[String(m.variant_id),m]));
 const normal=ordinaryInput.filter((l:any)=>!missMap.has(gid('ProductVariant',l.variant_id)));
 let normalQuoted:any[]=[];if(normal.length){const q=await proxy({...body,action:'quote_lines',payload:{...p,lines:normal}});normalQuoted=q.data?.lines||[]}
 const orderQuoted=await quoteClientCartLines(clientId,cartInput);
 const oos:any[]=[];for(const m of missing){const r=m.row,id=String(m.variant_id),qty=Number(m.quantity),price=money(r.price);oos.push({product_id:String(r.shopify_product_id||''),variant_id:id,title:String(r.title||'Prodotto'),variant_title:String(r.variant_title||''),vendor:String(r.vendor||''),product_type:String(r.product_type||''),sku:String(r.sku||''),barcode:String(r.barcode||''),image:String(r.image_url||''),inventory_item_id:r.id,price,quantity:qty,total:money(price*qty),list_price:price,discount_percent:0,discount_amount:0,discount_total:0,inventory_quantity:m.available_quantity,needs_order:true,missing_quantity:m.missing_quantity,fiscal_vat_code:String(r.vat_code||''),fiscal_item_type:r.category==='services'?'services':'goods'})}
 const allById=new Map([...normalQuoted,...oos,...orderQuoted].map((x:any)=>[String(x.variant_id||x.catalog_id),x]));
 const lines=linesIn.map((l:any)=>allById.get(String(l.variant_id))||allById.get(gid('ProductVariant',l.variant_id))).filter(Boolean);if(lines.length!==linesIn.length)throw new Error('Un articolo del carrello non è più disponibile. Ricarica la Cassa.');
 const subtotal=money(lines.reduce((s:number,x:any)=>s+Number(x.total||0),0));if(p.expected_total!=null&&cents(p.expected_total)!==cents(subtotal))throw new Error('Il totale è cambiato: aggiorna il carrello e riprova.');
 const client=await clientById(clientId);if(!client)throw new Error('Cliente non trovato');
 const stage=['deposit','balance','delivery_balance'].includes(norm(p.payment_stage))?norm(p.payment_stage):'balance',method=['cash','card','bank','other','pending'].includes(norm(p.payment_method))?norm(p.payment_method):'card',invoice=!!p.invoice_requested,ts=!!p.ts_requested,opposition=!!p.ts_opposition,code=norm(p.ts_expense_code)==='AA'?'AA':'AD',note=norm(p.note).slice(0,1000),lottery=cleanLottery(p.lottery_code);
 if(ts&&invoice)throw new Error('Per una spesa Sistema TS non usare la fattura elettronica.');if(lottery&&ts)throw new Error('Codice lotteria e codice fiscale per detrazione non possono essere usati nello stesso scontrino.');if(lottery&&invoice)throw new Error('Il codice lotteria non si usa con la fattura.');if(lottery&&method!=='card')throw new Error('Il codice lotteria richiede pagamento elettronico con carta.');if(lottery&&subtotal<1)throw new Error('Il codice lotteria richiede un acquisto di almeno 1,00 €.');
 let identity:any=null;if(ts){const base=norm(p.fiscal_code||client?.fiscal);identity={fiscal:fiscalCode(base)}}
 let paid=0;if(method!=='pending'){if(stage==='deposit'){paid=money(p.deposit_amount);if(!(paid>0&&paid<subtotal))throw new Error("L'acconto deve essere maggiore di 0 e inferiore al totale.")}else paid=subtotal}
 const due=money(Math.max(0,subtotal-paid)),paymentStatus=due>0?(paid>0?'partially_paid':'pending'):'paid',auto=p.auto_receipt===true&&!invoice&&method!=='pending'&&!lottery;let snapshot:any=null;if(auto&&paid>0)snapshot=paymentSnapshot(lines,linesIn,paid,0,identity,{ts,code,opposition});else if(auto&&subtotal===0)snapshot=zeroFiscalSnapshot(lines,linesIn);
 const missingItems=oos.map(x=>({variant_id:x.variant_id,title:x.title,variant_title:x.variant_title,sku:x.sku,quantity:x.quantity,available_quantity:x.inventory_quantity,missing_quantity:x.missing_quantity,unit_price:x.price}));
 const baseData={source:'optyker_pos_v2',checkout_request_id:requestId,pricing:{list_total:lines.reduce((s:number,x:any)=>s+money(x.list_price??x.price)*x.quantity,0),discount_total:lines.reduce((s:number,x:any)=>s+money(x.discount_total||0),0),total:subtotal},client_snapshot:client,fiscal_identity:identity,lottery_code:lottery,lines,missing_items:missingItems,payment_stage:stage,paid_now:paid,due_amount:due};
 let {data:sale,error:se}=await db.from('optyker_pos_sales').insert({client_id:client.id,operator_username:operator,payment_stage:stage,payment_method:method,payment_status:paymentStatus,status:'pending',subtotal,discount_total:money(baseData.pricing.discount_total),total:subtotal,paid_amount:paid,due_amount:due,currency:'EUR',note,invoice_requested:invoice,delivered_at:stage==='delivery_balance'&&due===0?new Date().toISOString():null,data:baseData}).select('*').single();if(se)throw se;
 try{
  const attrs:any[]=[{key:'Optyker operatore',value:operator},{key:'Metodo pagamento',value:method},{key:'Tipo pagamento',value:stage},{key:'Pagato ora',value:paid.toFixed(2)+' EUR'},{key:'Da saldare',value:due.toFixed(2)+' EUR'},{key:'Optyker sale id',value:String(sale.id)},{key:'Articoli da ordinare',value:String(missingItems.length)},{key:'Ordini laboratorio',value:String(orderQuoted.length)}];if(lottery)attrs.push({key:'Codice lotteria acquisito',value:'SI'});
  const input:any={lineItems:lines.map(safeVariantLine),note:note||`Vendita cassa Optyker · ${stage} · Operatore: ${operator}`,tags:['Optyker POS','Vendita negozio',...(orderQuoted.length?['Ordine laboratorio']:[]),...(missingItems.length?['Riordino necessario']:[])],customAttributes:attrs};if(client.shopify_customer_id)input.customerId=gid('Customer',client.shopify_customer_id);
  const created=await gql('mutation X($input:DraftOrderInput!){draftOrderCreate(input:$input){draftOrder{id name totalPriceSet{shopMoney{amount currencyCode}}} userErrors{message}}}',{input}),ce=created?.draftOrderCreate?.userErrors||[];if(ce.length)throw new Error(ce[0].message);const draft=created?.draftOrderCreate?.draftOrder;if(!draft?.id)throw new Error('Ordine Shopify non creato');await db.from('optyker_pos_sales').update({shopify_draft_order_id:draft.id,status:'draft',updated_at:new Date().toISOString()}).eq('id',sale.id);
  const comp=await gql('mutation X($id:ID!,$pending:Boolean!){draftOrderComplete(id:$id,paymentPending:$pending){draftOrder{id name status order{id name totalPriceSet{shopMoney{amount currencyCode}}}} userErrors{message}}}',{id:draft.id,pending:due>0}),ee=comp?.draftOrderComplete?.userErrors||[];if(ee.length)throw new Error(ee[0].message);const done=comp?.draftOrderComplete?.draftOrder,order=done?.order,finalTotal=money(order?.totalPriceSet?.shopMoney?.amount??subtotal);if(cents(finalTotal)!==cents(subtotal))throw new Error('Il totale Shopify è diverso dal carrello Optyker: vendita da verificare.');
  const stamp=new Date().toISOString(),updatedData={...baseData,shopify:{draft,order},due_amount:money(Math.max(0,finalTotal-paid))};const {data:patched,error:pu}=await db.from('optyker_pos_sales').update({status:due>0?'open_balance':'completed',shopify_order_id:String(order?.id||''),shopify_order_name:String(order?.name||draft?.name||''),total:finalTotal,paid_amount:paid,due_amount:money(Math.max(0,finalTotal-paid)),completed_at:order?.id?stamp:null,data:updatedData,updated_at:stamp}).eq('id',sale.id).select('*').single();if(pu)throw pu;sale=patched;
  const {error:itemsErr}=await db.from('optyker_pos_sale_items').insert(lines.map((x:any)=>({sale_id:sale.id,shopify_product_id:x.product_id||'',shopify_variant_id:String(x.variant_id||'').startsWith('gid://shopify/ProductVariant/')?x.variant_id:'',title:x.title,variant_title:x.variant_title||'',sku:x.sku||'',barcode:x.barcode||'',quantity:x.quantity,unit_price:x.price,total:x.total,data:{image:x.image||'',vendor:x.vendor||'',product_type:x.product_type||'',list_price:x.list_price??x.price,discount_percent:x.discount_percent||0,discount_amount:x.discount_amount||0,discount_total:x.discount_total||0,needs_order:!!x.needs_order,missing_quantity:x.missing_quantity||0,available_quantity:x.inventory_quantity??null,standard_price:x.standard_price??null,card_price:x.card_price??null,inventory_item_id:x.inventory_item_id??null,is_client_cart_order:!!x.is_client_cart_order,source_work_order_id:x.source_work_order_id||null,source_sheet_id:x.source_sheet_id||null}})));if(itemsErr)console.error(itemsErr.message);
  let payment:any=null,billing_invoice:any=null,ts_document:any=null;if(method!=='pending'&&(paid>0||subtotal===0)){payment=await createPayment(sale,client,operator,stage,method,paid,invoice,note,snapshot,{lottery_code:lottery,manual_lottery_required:!!lottery,zero_receipt:subtotal===0});if(invoice&&paid>0)billing_invoice=await createInvoiceDraft(sale,payment,client,operator,stage,method,paid);if(ts&&paid>0)ts_document=await createTsDocument(sale,payment,{...client,...identity},operator,stage,method,paid,code,opposition)}
  if(order?.id){const {error:oe}=await db.from('optyker_online_orders').upsert({shopify_order_id:String(order.id),order_name:String(order.name||''),shopify_customer_id:String(client.shopify_customer_id||''),client_id:client.id,financial_status:due>0?(paid>0?'partially_paid':'pending'):'paid',fulfillment_status:'unfulfilled',management_status:'managed',total:finalTotal,currency:'EUR',order_date:stamp,data:{source:'optyker_pos_v2',payment_method:method,payment_stage:stage,paid_amount:paid,due_amount:due,operator,client_snapshot:client,lines,lottery_code:lottery,missing_items:missingItems,invoice_requested:invoice,billing_invoice_id:billing_invoice?.id||null}},{onConflict:'shopify_order_id'});if(oe)console.error(oe.message)}
  return {...sale,payment,billing_invoice,ts_document,missing_items:missingItems,manual_lottery_required:!!lottery,zero_receipt:subtotal===0,zero_receipt_supported:subtotal!==0||!!snapshot,release:RELEASE};
 }catch(e){await db.from('optyker_pos_sales').update({status:'error',error_message:e instanceof Error?e.message:String(e),updated_at:new Date().toISOString()}).eq('id',sale.id);throw e}
}
