from pathlib import Path

p=Path('_site/index.html')
s=p.read_text(encoding='utf-8')
MARK='OPTYKER_APPOINTMENTS_UI_V7'
if MARK in s:
    raise SystemExit(0)
if 'OPTYKER_APPOINTMENTS_UI_V6' not in s or 'id="optykerAppointmentsPanel"' not in s:
    raise SystemExit('Agenda V6 non disponibile')

style=r'''<style id="optykerAppointmentsV7Css">/* OPTYKER_APPOINTMENTS_UI_V7 */
.oaCalendarModeV7{display:inline-flex;gap:5px;padding:4px;border:1px solid #d5e0e8;border-radius:10px;background:#f6f9fb;margin:10px 0 2px}.oaCalendarModeV7 button{border:0;border-radius:7px;padding:8px 12px;background:transparent;font-size:10px;font-weight:900;color:#526b7f;cursor:pointer}.oaCalendarModeV7 button.on{background:#1769aa;color:#fff}.oaStoreCalendarV7.hidden{display:none!important}.oaShiftCalendarV7{display:none}.oaShiftCalendarV7.open{display:block}.oaShiftToolbarV7{display:flex;gap:7px;align-items:center;flex-wrap:wrap;padding:12px 0}.oaShiftToolbarV7 input{height:38px;border:1px solid #cbd8e2;border-radius:8px;padding:6px 9px}.oaShiftDayTitleV7{font-size:18px;font-weight:900;color:#17324a;margin:4px 0 10px;text-transform:capitalize}.oaShiftGridV7{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:10px}.oaShiftCardV7{border:1px solid #dbe4ea;border-radius:12px;background:#fff;padding:12px;box-shadow:0 1px 5px #17324a0d}.oaShiftCardV7.sick{background:#fff7c7;border-color:#e8cb45}.oaShiftCardV7.vacation{background:#ffe2e2;border-color:#df7272}.oaShiftCardV7.rest{background:#dff2ff;border-color:#72b9e8}.oaShiftNameV7{font-size:14px;font-weight:900;color:#17324a;margin-bottom:8px}.oaShiftCardV7 label{display:block;font-size:9px;font-weight:900;color:#62788a;margin:7px 0 3px}.oaShiftCardV7 select,.oaShiftCardV7 input{width:100%;height:36px;border:1px solid #cbd8e2;border-radius:7px;padding:5px 7px;box-sizing:border-box;background:#fff}.oaShiftTimesV7{display:grid;grid-template-columns:1fr 1fr;gap:6px}.oaShiftSaveV7{width:100%;margin-top:10px}.oaLegendV7{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0 12px;font-size:9px;font-weight:800;color:#526b7f}.oaLegendV7 span{display:inline-flex;align-items:center;gap:5px}.oaLegendV7 i{width:12px;height:12px;border-radius:3px;display:inline-block;border:1px solid #bbc9d2}.oaLegendV7 .yl{background:#fff7c7}.oaLegendV7 .rd{background:#ffe2e2}.oaLegendV7 .bl{background:#dff2ff}
.oaSetV7Force{display:block!important;visibility:visible!important;opacity:1!important}.oaStoreHoursV7{display:grid;gap:7px}.oaStoreHourV7{display:grid;grid-template-columns:105px 75px repeat(4,minmax(82px,1fr));gap:6px;align-items:center;border:1px solid #e1e8ed;border-radius:9px;padding:8px;background:#fff}.oaStoreHourV7 b{font-size:10px;color:#17324a}.oaStoreHourV7 input,.oaStoreHourV7 select{height:34px;border:1px solid #cbd8e2;border-radius:7px;padding:4px 6px;min-width:0}.oaStoreHoursHelpV7{font-size:9px;color:#6d8291;margin-bottom:7px;line-height:1.45}
@media(max-width:950px){.oaShiftGridV7{grid-template-columns:1fr}.oaStoreHourV7{grid-template-columns:95px 70px 1fr 1fr}.oaStoreHourV7 .v7second{grid-column:auto}}
@media(max-width:620px){.oaStoreHourV7{grid-template-columns:1fr 1fr}.oaShiftTimesV7{grid-template-columns:1fr 1fr}}
</style>'''

script=r'''<script id="optykerAppointmentsV7Js">(function(){/* OPTYKER_APPOINTMENTS_UI_V7 */
var DAYS=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];
var shiftDate='';
function E(i){return document.getElementById(i)}
function X(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function cloud(){if(!window.OPTYKER_CLOUD||!OPTYKER_CLOUD.username)throw Error('Sessione non autenticata');return OPTYKER_CLOUD}
function api(action,payload){var c=cloud();if(!c.username||!c.password){return Promise.reject(Error('Sessione non autenticata'))}return fetch(c.root+'/rest/v1/rpc/optyker_agenda_v6_api',{method:'POST',headers:{'Content-Type':'application/json','apikey':c.key,'Authorization':'Bearer '+c.key},body:JSON.stringify({p_username:c.username,p_password:c.password,p_action:action,p_payload:payload||{}})}).then(function(r){if(!r.ok)throw Error('Server '+r.status);return r.json()}).then(function(x){if(!x||x.ok===false){if(/non autorizzato/i.test(String(x&&x.error||''))){try{if(window.optykerShowLogin)window.optykerShowLogin()}catch(z){}}throw Error(x&&x.error||'Errore agenda')}return x})}
function msg(t,b){var e=E('oaSettingsStatus');if(e){e.textContent=t||'';e.className='oaStatus'+(b?' bad':'')}}
function z(n){return String(n).padStart(2,'0')}function iso(d){return d.getFullYear()+'-'+z(d.getMonth()+1)+'-'+z(d.getDate())}function plus(v,n){var d=new Date(v+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)}function t5(v){return v?String(v).slice(0,5):''}
function shiftClass(s){return s==='sick'?'sick':s==='vacation'?'vacation':s==='rest'?'rest':''}
function ensureCalendar(){var panel=E('optykerAppointmentsPanel');if(!panel)return;
  if(!E('oaCalendarModeV7')){var head=panel.querySelector('.oaHead');if(head){var mode=document.createElement('div');mode.id='oaCalendarModeV7';mode.className='oaCalendarModeV7';mode.innerHTML='<button id="oaModeStoreV7" type="button">Negozio</button><button id="oaModeShiftV7" type="button">Turni e orari</button>';head.insertAdjacentElement('afterend',mode);E('oaModeStoreV7').onclick=function(){showMode('store')};E('oaModeShiftV7').onclick=function(){showMode('shifts')}}}
  if(!E('oaStoreCalendarV7')){var store=document.createElement('div');store.id='oaStoreCalendarV7';store.className='oaStoreCalendarV7';var tb=panel.querySelector('.oaToolbar'),st=E('oaStatus'),cal=E('oaCalendar');if(tb)store.appendChild(tb);if(st)store.appendChild(st);if(cal)store.appendChild(cal);panel.appendChild(store)}
  if(!E('oaShiftCalendarV7')){var sh=document.createElement('div');sh.id='oaShiftCalendarV7';sh.className='oaShiftCalendarV7';sh.innerHTML='<div class="oaShiftToolbarV7"><button id="oaShiftPrevV7" class="secondary" type="button">‹</button><button id="oaShiftTodayV7" class="secondary" type="button">Oggi</button><button id="oaShiftNextV7" class="secondary" type="button">›</button><input id="oaShiftDateV7" type="date"></div><div id="oaShiftDayTitleV7" class="oaShiftDayTitleV7"></div><div class="oaLegendV7"><span><i class="yl"></i>Malattia</span><span><i class="rd"></i>Ferie</span><span><i class="bl"></i>Giorno di riposo</span></div><div id="oaShiftGridV7" class="oaShiftGridV7"></div><div id="oaShiftStatusV7" class="oaStatus"></div>';panel.appendChild(sh);shiftDate=iso(new Date());E('oaShiftDateV7').value=shiftDate;E('oaShiftDateV7').onchange=function(){shiftDate=this.value;loadShiftDay()};E('oaShiftPrevV7').onclick=function(){shiftDate=plus(shiftDate,-1);E('oaShiftDateV7').value=shiftDate;loadShiftDay()};E('oaShiftNextV7').onclick=function(){shiftDate=plus(shiftDate,1);E('oaShiftDateV7').value=shiftDate;loadShiftDay()};E('oaShiftTodayV7').onclick=function(){shiftDate=iso(new Date());E('oaShiftDateV7').value=shiftDate;loadShiftDay()}}
  var preferred=localStorage.getItem('optyker_calendar_mode_v7')==='shifts'?'shifts':'store';applyMode(preferred,false)
}
function applyMode(which,save){var store=E('oaStoreCalendarV7'),sh=E('oaShiftCalendarV7'),bs=E('oaModeStoreV7'),bh=E('oaModeShiftV7'),newb=E('oaNew');if(store)store.classList.toggle('hidden',which!=='store');if(sh)sh.classList.toggle('open',which==='shifts');if(bs)bs.classList.toggle('on',which==='store');if(bh)bh.classList.toggle('on',which==='shifts');if(newb)newb.style.display=which==='store'?'':'none';if(save!==false)localStorage.setItem('optyker_calendar_mode_v7',which);if(which==='shifts'&&!E('optykerShiftsMonthlyV16Js'))loadShiftDay()}
function showMode(which){applyMode(which,true)}
function loadShiftDay(){if(!E('oaShiftGridV7'))return;if(!shiftDate)shiftDate=iso(new Date());var stat=E('oaShiftStatusV7');if(stat)stat.textContent='Caricamento...';api('staff_day_get',{date:shiftDate}).then(function(x){var d=new Date(shiftDate+'T12:00:00');E('oaShiftDayTitleV7').textContent=d.toLocaleDateString('it-IT',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});var data=x.data||[];E('oaShiftGridV7').innerHTML=data.map(function(r){var st=r.status||'work';return '<div class="oaShiftCardV7 '+shiftClass(st)+'" data-op="'+X(r.operator_username)+'"><div class="oaShiftNameV7">'+X(r.operator_username)+'</div><label>Stato</label><select class="v7status"><option value="work" '+(st==='work'?'selected':'')+'>Turno di lavoro</option><option value="sick" '+(st==='sick'?'selected':'')+'>Malattia</option><option value="vacation" '+(st==='vacation'?'selected':'')+'>Ferie</option><option value="rest" '+(st==='rest'?'selected':'')+'>Giorno di riposo</option></select><label>Prima fascia</label><div class="oaShiftTimesV7"><input class="v7s1" type="time" value="'+X(t5(r.start_time))+'"><input class="v7e1" type="time" value="'+X(t5(r.end_time))+'"></div><label>Seconda fascia</label><div class="oaShiftTimesV7"><input class="v7s2" type="time" value="'+X(t5(r.start_time_2))+'"><input class="v7e2" type="time" value="'+X(t5(r.end_time_2))+'"></div><button class="primary oaShiftSaveV7" type="button">Salva</button></div>'}).join('');E('oaShiftGridV7').querySelectorAll('.oaShiftCardV7').forEach(function(card){var sel=card.querySelector('.v7status');function paint(){card.classList.remove('sick','vacation','rest');var c=shiftClass(sel.value);if(c)card.classList.add(c);var off=sel.value!=='work';card.querySelectorAll('input[type=time]').forEach(function(i){i.disabled=off})}sel.onchange=paint;paint();card.querySelector('.oaShiftSaveV7').onclick=function(){var b=this;b.disabled=true;api('staff_day_save',{date:shiftDate,operator_username:card.dataset.op,status:sel.value,start_time:card.querySelector('.v7s1').value,end_time:card.querySelector('.v7e1').value,start_time_2:card.querySelector('.v7s2').value,end_time_2:card.querySelector('.v7e2').value}).then(function(){if(stat)stat.textContent='Turno salvato.';loadShiftDay()}).catch(function(e){if(stat)stat.textContent=e.message}).finally(function(){b.disabled=false})}});if(stat)stat.textContent=''}).catch(function(e){if(stat)stat.textContent=e.message})}
function findSet(title){var sets=document.querySelectorAll('.oaSet');for(var i=0;i<sets.length;i++){var t=sets[i].querySelector('.oaSetTitle span');if(t&&t.textContent.trim().toLowerCase()===title.toLowerCase())return sets[i]}return null}
function ensureSettings(){var sets=document.querySelector('.oaSets');if(!sets)return;var studios=findSet('Studi');if(studios){studios.classList.add('oaSetV7Force');studios.style.setProperty('display','block','important');studios.style.setProperty('visibility','visible','important');studios.style.setProperty('opacity','1','important')}
  var rules=findSet('Disponibilità');if(!E('oaStoreSetV7')){var box=document.createElement('div');box.id='oaStoreSetV7';box.className='oaSet full oaSetV7Force';box.innerHTML='<div class="oaSetTitle"><span>Negozio</span></div><div class="oaStoreHoursHelpV7">Da questa sezione stabilisci i giorni e le fasce orarie in cui il negozio accetta appuntamenti. Puoi impostare una prima e una seconda fascia per ogni giorno.</div><div id="oaStoreHoursV7" class="oaStoreHoursV7"></div>';if(rules)sets.insertBefore(box,rules);else sets.appendChild(box);loadStoreHours()}else if(E('oaStoreHoursV7')&&!E('oaStoreHoursV7').children.length)loadStoreHours()
}
function loadStoreHours(){var root=E('oaStoreHoursV7');if(!root)return;api('store_hours_list',{}).then(function(x){var a=x.data||[];root.innerHTML=a.map(function(r){return '<div class="oaStoreHourV7" data-day="'+r.weekday+'"><b>'+DAYS[r.weekday-1]+'</b><select class="v7active"><option value="true" '+(r.active?'selected':'')+'>Aperto</option><option value="false" '+(!r.active?'selected':'')+'>Chiuso</option></select><input class="v7h1s" type="time" value="'+X(t5(r.start_time))+'"><input class="v7h1e" type="time" value="'+X(t5(r.end_time))+'"><input class="v7h2s v7second" type="time" value="'+X(t5(r.start_time_2))+'"><input class="v7h2e v7second" type="time" value="'+X(t5(r.end_time_2))+'"></div>'}).join('')}).catch(function(e){msg(e.message,true)})}
function boot(){ensureCalendar();ensureSettings();setTimeout(ensureSettings,250);setTimeout(ensureSettings,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.addEventListener('pageshow',function(){ensureCalendar();ensureSettings()})
})();</script>'''

h=s.find('</head>')
if h<0: raise SystemExit('head non trovato')
s=s[:h]+style+s[h:]
b=s.rfind('</body>')
if b<0: raise SystemExit('body non trovato')
s=s[:b]+script+s[b:]
p.write_text(s,encoding='utf-8')
if MARK not in s or 'Turni e orari' not in s or 'oaStoreSetV7' not in s:
    raise SystemExit('Agenda V7 non inserita')
print('Appointments V7 store calendar and staff shifts OK')
