import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')||'',A=Deno.env.get('SUPABASE_ANON_KEY')||'',S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const BOOK=`${U}/functions/v1/optyker-appointments-booking`;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
async function user(req:Request){const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!t)throw Error('AUTH_REQUIRED');const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:A,Authorization:`Bearer ${t}`}});if(!r.ok)throw Error('AUTH_INVALID');const x=await r.json();if(!x?.email)throw Error('EMAIL_REQUIRED');return {id:x.id,email:String(x.email).trim().toLowerCase(),verified:!!x.email_confirmed_at}}
async function db(path:string,opt:any={}){const r=await fetch(`${U}/rest/v1/${path}`,{...opt,headers:{apikey:S,Authorization:`Bearer ${S}`,'Content-Type':'application/json',...(opt.headers||{})}});const x=await r.json().catch(()=>null);if(!r.ok)throw Error(x?.message||`DB_${r.status}`);return x}
async function rpc(name:string,body:any){return db(`rpc/${name}`,{method:'POST',body:JSON.stringify(body||{})})}
const q=(v:any)=>encodeURIComponent(String(v??''));
async function identity(u:any){const o=await db(`optyker_operator_profiles?select=username,email&email=ilike.${q(u.email)}&limit=1`);if(Array.isArray(o)&&o[0])return {role:'staff',operator:o[0]};const c=await db(`optyker_clients?select=id,name,surname,email,phone&email=ilike.${q(u.email)}&order=updated_at.desc&limit=1`);if(Array.isArray(c)&&c[0])return {role:'customer',client:c[0]};return {role:'unlinked'}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return out({ok:true});if(req.method!=='POST')return out({ok:false,error:'METHOD_NOT_ALLOWED'},405);try{const u=await user(req),id:any=await identity(u),b=await req.json().catch(()=>({})),action=String(b.action||''),p=b.payload||{};if(id.role==='unlinked')return out({ok:false,error:'EMAIL_NOT_LINKED'},403);
if(id.role==='customer'){if(action==='history')return out(await rpc('optyker_appointment_client_history',{p_email:u.email}));if(action==='booking')return out({ok:true,url:BOOK+'?source=mobile&first_name='+q(id.client.name)+'&last_name='+q(id.client.surname)+'&email='+q(id.client.email)+'&phone='+q(id.client.phone)});return out({ok:false,error:'ACTION_NOT_ALLOWED'},403)}
if(id.role==='staff'){if(action==='duration'){
if(!u.verified||String(id.operator.email||'').trim().toLowerCase()!==u.email)return out({ok:false,error:'EMAIL_NOT_VERIFIED_OR_LINKED'},403);
return out(await rpc('optyker_appointment_set_duration',{p_username:id.operator.username,p_appointment_id:p.id,p_minutes:p.duration_minutes,p_expected_updated_at:p.expected_updated_at||null}));
}const call=(a:string,payload:any)=>rpc('optyker_appointments_api',{p_username:id.operator.username,p_password:'',p_action:a,p_payload:payload||{}});if(action==='bootstrap')return out(await call('bootstrap',{}));if(action==='list')return out(await call('list',p));if(action==='create')return out(await call('appointment_create',p));if(action==='status')return out(await call('appointment_status',p));if(action==='update')return out(await rpc('optyker_appointment_staff_reschedule',{p_username:id.operator.username,p_appointment_id:p.id,p_payload:p}));if(action==='booking')return out({ok:true,url:BOOK+'?source=mobile'});return out({ok:false,error:'ACTION_NOT_ALLOWED'},403)}return out({ok:false,error:'ROLE_NOT_SUPPORTED'},403)}catch(e){const m=e instanceof Error?e.message:String(e);return out({ok:false,error:m},m.startsWith('AUTH_')?401:500)}});
