-- Synthetic database only. No real users, payments, credentials or devices.
create role anon;create role authenticated;create role service_role;
create table public.optyker_cash_openings(id uuid primary key default gen_random_uuid(),register_code text not null default 'main',business_date date not null,operator_username text default '',opening_cash numeric default 0,opening_checks numeric default 0,notes text default '',opened_at timestamptz default clock_timestamp(),updated_at timestamptz default clock_timestamp(),unique(register_code,business_date));
create table public.optyker_cash_closures(id uuid primary key default gen_random_uuid(),register_code text default 'main',business_date date,operator_username text default '',opening_cash numeric default 0,opening_checks numeric default 0,cash_expected numeric default 0,cash_counted numeric default 0,checks_counted numeric default 0,cash_difference numeric default 0,card_total numeric default 0,bank_total numeric default 0,other_total numeric default 0,total_collected numeric default 0,payments_count int default 0,sales_count int default 0,pending_total numeric default 0,pending_count int default 0,turnover_total numeric default 0,receipts_total numeric default 0,receipts_count int default 0,invoice_payments_total numeric default 0,bank_deposit_cash numeric default 0,bank_deposit_checks numeric default 0,safe_deposit_cash numeric default 0,safe_deposit_checks numeric default 0,next_opening_cash numeric default 0,next_opening_checks numeric default 0,notes text default '',snapshot jsonb default '{}',closed_at timestamptz default clock_timestamp(),created_at timestamptz default clock_timestamp(),unique(register_code,business_date));
create table public.optyker_rch_remote_commands(id uuid primary key default gen_random_uuid(),kind text,serial text,state text,requested_by text,requested_at timestamptz default clock_timestamp(),expires_at timestamptz,payload jsonb default '{}',result jsonb default '{}',error text default '');
create table public.optyker_rch_connectors(id uuid default gen_random_uuid(),active boolean,serial text,last_seen_at timestamptz,last_status jsonb,connector_version text);
create table public.fixture_day_flows(day date primary key,total numeric,cash numeric,card numeric,n int);
create function public.optyker_cash_day_metrics(p_business_date date) returns jsonb language sql stable as $$
 select jsonb_build_object('business_date',p_business_date,'total_collected',coalesce(f.total,0),'cash_total',coalesce(f.cash,0),'card_total',coalesce(f.card,0),'bank_total',0,'other_total',0,'invoice_payments_total',0,'payments_count',coalesce(f.n,0),'turnover_total',coalesce(f.total,0),'sales_count',coalesce(f.n,0),'receipts_total',coalesce(f.total,0),'receipts_count',coalesce(f.n,0),'receipt_cash_total',coalesce(f.cash,0),'receipt_card_total',coalesce(f.card,0),'receipt_bank_total',0,'receipt_other_total',0,'pending_count',0,'pending_total',0,'by_stage','{}'::jsonb,'opening',(select to_jsonb(o) from optyker_cash_openings o where business_date=p_business_date),'closure',(select to_jsonb(c) from optyker_cash_closures c where business_date=p_business_date),'opened',exists(select 1 from optyker_cash_openings where business_date=p_business_date),'closed',exists(select 1 from optyker_cash_closures where business_date=p_business_date),'suggested_opening_cash',coalesce((select next_opening_cash from optyker_cash_closures where business_date<p_business_date order by business_date desc limit 1),70),'suggested_opening_checks',0) from (select p_business_date day) x left join fixture_day_flows f on f.day=x.day;
$$;
